/** @file ClassificationConstrainedSubPlanType.cpp
 *
 * @warning This file is automatically generated, edit at your own risk
 *
 * This file was generated on 04/01/2024 at 02:25:22 PM
 *
 * <pre>
 * Unclassified               U N C L A S S I F I E D               Unclassified
 *
 * DISTRIBUTION STATEMENT D: Distribution authorized to Department of Defense
 *    and U.S. DoD contractors only, Critical Technology, Export Controlled,
 *    26 January 2023. Other requests for this document shall be referred to
 *    AFLCMC/XA (OAMO), Wright-Patterson AFB OH 45433.
 *
 * DESTRUCTION NOTICE: Destroy by any method that will prevent disclosure of
 *    contents or reconstruction of the document.
 *
 * WARNING - This document contains technical data whose export is restricted
 *    by the Arms Export Control Act (Section 2751 of Title 22, United States
 *    Code) or the Export Control Reform Act of 2018 (Chapter 58 Sections
 *    4801-4852 of Title 50, United States Code). Violations of these export
 *    laws are subject to severe criminal penalties. Disseminate in accordance
 *    with provisions of DoD Directive 5230.25 and DoD Instruction 2040.02.
 *
 * Controlled by: USAF
 * Controlled by: AFLCMC/XA (OAMO)
 * CUI Category(ies): CTI, EXPT
 * Distribution Statement D
 * POC: Wayne Artuso, 937-713-5124
 *
 * CUI//SP-CTI/SP-EXPT
 * </pre>
 *
 */

#include "extjson_uci/type/ClassificationConstrainedSubPlanType.h"

#include <string>

#include <boost/optional/optional.hpp>
#include <boost/property_tree/ptree.hpp>

#include "extjson_uci/type/ComparableRankingType.h"
#include "extjson_uci/type/ProductFilterType.h"
#include "extjson_uci/type/SecurityInformationType.h"
#include "extjson_uci/util/SerializationHelpers.h"
#include "uci/type/ClassificationConstrainedSubPlanType.h"

/**  */
namespace extjson_uci {

/** The namespace in which all generated data types are declared */
namespace type {

/**  */
namespace ClassificationConstrainedSubPlanType_Names {

constexpr const char* Extern_Type_Name{"ClassificationConstrainedSubPlanType"};
constexpr const char* SecurityInformation_Name{"SecurityInformation"};
constexpr const char* ConstrainedSubPlanRank_Name{"ConstrainedSubPlanRank"};
constexpr const char* Filter_Name{"Filter"};

} // namespace ClassificationConstrainedSubPlanType_Names

bool ClassificationConstrainedSubPlanType::deserialize(const boost::property_tree::ptree& propTree, uci::type::ClassificationConstrainedSubPlanType& accessor, std::string& nodeName, std::string& nsPrefix, const bool topLevel) {
  nodeName = ClassificationConstrainedSubPlanType_Names::Extern_Type_Name;
  const boost::property_tree::ptree& node = (topLevel ? propTree.ordered_begin()->second : propTree);
  for (const boost::property_tree::ptree::value_type& valueType : node.get_child("")) {
    if (valueType.first == nsPrefix + ClassificationConstrainedSubPlanType_Names::SecurityInformation_Name) {
      SecurityInformationType::deserialize(valueType.second, accessor.getSecurityInformation(), nodeName, nsPrefix);
    } else if (valueType.first == nsPrefix + ClassificationConstrainedSubPlanType_Names::ConstrainedSubPlanRank_Name) {
      ComparableRankingType::deserialize(valueType.second, accessor.getConstrainedSubPlanRank(), nodeName, nsPrefix);
    } else if (valueType.first == nsPrefix + ClassificationConstrainedSubPlanType_Names::Filter_Name) {
      uci::type::ClassificationConstrainedSubPlanType::Filter& boundedList = accessor.getFilter();
      const uci::type::ClassificationConstrainedSubPlanType::Filter::size_type boundedListSize{boundedList.size()};
      boundedList.resize(boundedListSize + 1);
      ProductFilterType::deserialize(valueType.second, boundedList.at(boundedListSize), nodeName, nsPrefix);
    }
  }
  return true;
}

std::string ClassificationConstrainedSubPlanType::serialize(const uci::type::ClassificationConstrainedSubPlanType& accessor, boost::property_tree::ptree& propTree, const std::string& nodeName, const bool createNode, const bool addTypeAttribute, const bool /*checkIfDerivation*/, const bool /*topLevel*/) {
  std::string generatedNodeName{nodeName.empty() ? ClassificationConstrainedSubPlanType_Names::Extern_Type_Name : nodeName};
  boost::property_tree::ptree newNode;
  boost::property_tree::ptree& node = (createNode ? newNode : propTree);
  if (addTypeAttribute) {
    extjson_uci::util::SerializationHelpers::addTypeAttribute(node, ClassificationConstrainedSubPlanType_Names::Extern_Type_Name);
  }
  SecurityInformationType::serialize(accessor.getSecurityInformation(), node, ClassificationConstrainedSubPlanType_Names::SecurityInformation_Name);
  ComparableRankingType::serialize(accessor.getConstrainedSubPlanRank(), node, ClassificationConstrainedSubPlanType_Names::ConstrainedSubPlanRank_Name);
  {
    const uci::type::ClassificationConstrainedSubPlanType::Filter& boundedList = accessor.getFilter();
    for (uci::type::ClassificationConstrainedSubPlanType::Filter::size_type i = 0, end = boundedList.size(); i < end; ++i) {
      ProductFilterType::serialize(boundedList.at(i), node, ClassificationConstrainedSubPlanType_Names::Filter_Name);
    }
  }
  if (createNode) {
    propTree.add_child(boost::property_tree::ptree::path_type(generatedNodeName, '#'), node);
  }
  return generatedNodeName;
}

} // namespace type

} // namespace extjson_uci

