/** @file EventWindowChoiceType.h
 *
 * @warning This file is automatically generated, edit at your own risk
 *
 * This file was generated on 04/01/2024 at 02:25:07 PM
 *
 * <pre>
 * Unclassified               U N C L A S S I F I E D               Unclassified
 *
 * DISTRIBUTION STATEMENT D: Distribution authorized to Department of Defense
 *    and U.S. DoD contractors only, Critical Technology, Export Controlled,
 *    26 January 2023. Other requests for this document shall be referred to
 *    AFLCMC/XA (OAMO), Wright-Patterson AFB OH 45433.
 *
 * DESTRUCTION NOTICE: Destroy by any method that will prevent disclosure of
 *    contents or reconstruction of the document.
 *
 * WARNING - This document contains technical data whose export is restricted
 *    by the Arms Export Control Act (Section 2751 of Title 22, United States
 *    Code) or the Export Control Reform Act of 2018 (Chapter 58 Sections
 *    4801-4852 of Title 50, United States Code). Violations of these export
 *    laws are subject to severe criminal penalties. Disseminate in accordance
 *    with provisions of DoD Directive 5230.25 and DoD Instruction 2040.02.
 *
 * Controlled by: USAF
 * Controlled by: AFLCMC/XA (OAMO)
 * CUI Category(ies): CTI, EXPT
 * Distribution Statement D
 * POC: Wayne Artuso, 937-713-5124
 *
 * CUI//SP-CTI/SP-EXPT
 * </pre>
 *
 */

#ifndef UCI_TYPE_EVENTWINDOWCHOICETYPE_H
#define UCI_TYPE_EVENTWINDOWCHOICETYPE_H

#include "../base/Accessor.h"
#include "../base/export.h"
#include "AnglePositiveType.h"
#include "DistanceType.h"
#include "DurationType.h"

/** The namespace in which all UCI data types are declared */
namespace uci {

/** The namespace in which all base data types are declared */
namespace base {

class AbstractServiceBusConnection;

} // namespace base
} // namespace uci

/** The namespace in which all UCI data types are declared */
namespace uci {

/** The namespace in which all generated data types are declared */
namespace type {

/** Provides a choice of event window size definitions. */
class EventWindowChoiceType : public virtual uci::base::Accessor {
public:

  /** This method constructs a new EventWindowChoiceType.
    *
    * @param abstractServiceBusConnection The pointer to the Abstract Service Bus Connection that provides the support
    *      required to create objects.
    * @return The newly contructed EventWindowChoiceType.
    */
  static UCI_EXPORT EventWindowChoiceType& create(uci::base::AbstractServiceBusConnection* abstractServiceBusConnection = NULL);

  /** This method constructs a new EventWindowChoiceType initializing the data accessed by the new EventWindowChoiceType
    * using the data accessed by the specified EventWindowChoiceType (cloning).
    *
    * @param accessor The EventWindowChoiceType that provides access to the data that is to be used to initialize the data
    *      accessed by the new created EventWindowChoiceType.
    * @param abstractServiceBusConnection The pointer to the Abstract Service Bus Connection that provides the support
    *      required to create objects.
    * @return The newly contructed EventWindowChoiceType.
    */
  static UCI_EXPORT EventWindowChoiceType& create(const EventWindowChoiceType& accessor, uci::base::AbstractServiceBusConnection* abstractServiceBusConnection = NULL);

  /** This method destroys the specified EventWindowChoiceType. Use of the specified accessor after it has been destroyed
    * will result in undefined behavior.
    *
    * @param accessor The EventWindowChoiceType that is to be destroyed.
    */
  static UCI_EXPORT void destroy(EventWindowChoiceType& accessor);

  /** Returns this accessor's type constant, i.e. eventWindowChoiceType.
    *
    * @return This accessor's type constant, i.e. eventWindowChoiceType.
    */
  virtual uci::base::accessorType::AccessorType getAccessorType() const noexception {
    return uci::type::accessorType::eventWindowChoiceType;
  }

  /** Returns the version that was initialized from the uci:version attribute of EventWindowChoiceType.
    *
    * @return The version that was initialized from the uci:version attribute of EventWindowChoiceType.
    */
  static std::string getUCITypeVersion() {
    return "001.000.000.000";
  }

  /** Initializes the contents of this accessor by copying the contents of the specified accessor.
    *
    * @param accessor The accessor whose contents are to be used to initialize the contents of this accessor.
    */
  virtual void copy(const EventWindowChoiceType& accessor) = 0;

  /** The following enumeration is used to identify which element of this Choice has been chosen. */
  enum EventWindowChoiceTypeChoice {
    EVENTWINDOWCHOICETYPE_CHOICE_NONE,
    EVENTWINDOWCHOICETYPE_CHOICE_WINDOWANGLE,
    EVENTWINDOWCHOICETYPE_CHOICE_WINDOWDURATION,
    EVENTWINDOWCHOICETYPE_CHOICE_WINDOWRADIUS
  };

  /** This method returns this choice's "selection ordinal." A choice's "selection ordinal" is used to specify which
    * element in the choice is chosen to be active.
    *
    * @return The selected item's enumerated value.
    */
  virtual EventWindowChoiceTypeChoice getEventWindowChoiceTypeChoiceOrdinal() const = 0;

  /** This method is used to set this choice's "selection ordinal." A choice's "selection ordinal" is used to specify which
    * element in the choice is chosen to be active. There are two mechanisms that can be used to set a choice's "selection
    * ordinal." The first mechanism is by invoking this method. The second mechanism is by invoking one of the set methods
    * associated with one of the elements contained in this choice. Once this method is invoked, the value returned by
    * getEventWindowChoiceTypeChoiceOrdinal() will be the ordinal specified when this method was invoked. In addition, the
    * access methods associated with the chosen element will be enabled and will provide access to the chosen element.
    *
    * @param chosenElementOrdinal The ordinal to set this choice's selected ordinal to.
    * @param type = uci::base::accessorType::null The type of data that is to be made available when the ordinal is set.
    *      The use of this parameter provides support for inheritable types. This parameter defaults to
    *      uci::base::accessorType::null that is used to indicate that the access methods associated with the chosen
    *      element shall provide access to data of the type that was specified for that element in the choice in the OMS
    *      schema, i.e. the chosen element's base type. If specified, this field must either be a type ID associated with
    *      the chosen element's base type or a type ID associated with a type that is derived from the chosen element's
    *      base type.
    * @return A reference to the object on which this method was called.
    */
  virtual uci::type::EventWindowChoiceType& setEventWindowChoiceTypeChoiceOrdinal(EventWindowChoiceTypeChoice chosenElementOrdinal, uci::base::accessorType::AccessorType type = uci::base::accessorType::null) = 0;

  /** Returns the value of the SimplePrimitive data type identified by WindowAngle.
    *
    * @return The value of the simple primitive data type identified by WindowAngle.
    */
  virtual uci::type::AnglePositiveTypeValue getWindowAngle() const = 0;

  /** Sets the value of the SimplePrimitive data type identified by WindowAngle.
    *
    * @param value The value to set the SimplePrimitve data type to.
    * @return A reference to the object on which this method was called.
    */
  virtual uci::type::EventWindowChoiceType& setWindowAngle(uci::type::AnglePositiveTypeValue value) = 0;

  /** Returns whether this choice's "selection ordinal" is set to the choice identified by WindowAngle.
    *
    * @return True if this choice's "selection ordinal" is set to the choice identified by WindowAngle, false otherwise.
    */
  virtual bool isWindowAngle() const = 0;

  /** Returns the value of the SimplePrimitive data type identified by WindowDuration.
    *
    * @return The value of the simple primitive data type identified by WindowDuration.
    */
  virtual uci::type::DurationTypeValue getWindowDuration() const = 0;

  /** Sets the value of the SimplePrimitive data type identified by WindowDuration.
    *
    * @param value The value to set the SimplePrimitve data type to.
    * @return A reference to the object on which this method was called.
    */
  virtual uci::type::EventWindowChoiceType& setWindowDuration(uci::type::DurationTypeValue value) = 0;

  /** Returns whether this choice's "selection ordinal" is set to the choice identified by WindowDuration.
    *
    * @return True if this choice's "selection ordinal" is set to the choice identified by WindowDuration, false otherwise.
    */
  virtual bool isWindowDuration() const = 0;

  /** Returns the value of the SimplePrimitive data type identified by WindowRadius.
    *
    * @return The value of the simple primitive data type identified by WindowRadius.
    */
  virtual uci::type::DistanceTypeValue getWindowRadius() const = 0;

  /** Sets the value of the SimplePrimitive data type identified by WindowRadius.
    *
    * @param value The value to set the SimplePrimitve data type to.
    * @return A reference to the object on which this method was called.
    */
  virtual uci::type::EventWindowChoiceType& setWindowRadius(uci::type::DistanceTypeValue value) = 0;

  /** Returns whether this choice's "selection ordinal" is set to the choice identified by WindowRadius.
    *
    * @return True if this choice's "selection ordinal" is set to the choice identified by WindowRadius, false otherwise.
    */
  virtual bool isWindowRadius() const = 0;

protected:

  /** The constructor [only available to derived classes]. */
  EventWindowChoiceType() {
  }

  /** The destructor [only available to derived classes]. */
  ~EventWindowChoiceType() {
  }

  /** The copy constructor [only available to derived classes].
    *
    * @param rhs The EventWindowChoiceType to copy from.
    */
  EventWindowChoiceType(const EventWindowChoiceType& rhs) {
    (void)rhs;
  }

  /** The assignment operator. Sets the contents of this EventWindowChoiceType to the contents of the EventWindowChoiceType
    * on the right hand side (rhs) of the assignment operator [only available to derived classes].
    *
    * @param rhs The EventWindowChoiceType on the right hand side (rhs) of the assignment operator whose contents are used
    *      to set the contents of this EventWindowChoiceType.
    * @return A reference to this EventWindowChoiceType.
    */
  EventWindowChoiceType& operator=(const EventWindowChoiceType& rhs) {
    (void)rhs;

    return *this;
  }

};

} // namespace type
} // namespace uci

#endif // UCI_TYPE_EVENTWINDOWCHOICETYPE_H

