/** @file PO_ComponentWindowType.h
 *
 * @warning This file is automatically generated, edit at your own risk
 *
 * This file was generated on 04/01/2024 at 02:25:07 PM
 *
 * <pre>
 * Unclassified               U N C L A S S I F I E D               Unclassified
 *
 * DISTRIBUTION STATEMENT D: Distribution authorized to Department of Defense
 *    and U.S. DoD contractors only, Critical Technology, Export Controlled,
 *    26 January 2023. Other requests for this document shall be referred to
 *    AFLCMC/XA (OAMO), Wright-Patterson AFB OH 45433.
 *
 * DESTRUCTION NOTICE: Destroy by any method that will prevent disclosure of
 *    contents or reconstruction of the document.
 *
 * WARNING - This document contains technical data whose export is restricted
 *    by the Arms Export Control Act (Section 2751 of Title 22, United States
 *    Code) or the Export Control Reform Act of 2018 (Chapter 58 Sections
 *    4801-4852 of Title 50, United States Code). Violations of these export
 *    laws are subject to severe criminal penalties. Disseminate in accordance
 *    with provisions of DoD Directive 5230.25 and DoD Instruction 2040.02.
 *
 * Controlled by: USAF
 * Controlled by: AFLCMC/XA (OAMO)
 * CUI Category(ies): CTI, EXPT
 * Distribution Statement D
 * POC: Wayne Artuso, 937-713-5124
 *
 * CUI//SP-CTI/SP-EXPT
 * </pre>
 *
 */

#ifndef UCI_TYPE_PO_COMPONENTWINDOWTYPE_H
#define UCI_TYPE_PO_COMPONENTWINDOWTYPE_H

#include "uci/base/Accessor.h"
#include "uci/base/BoundedList.h"
#include "uci/base/UnsignedIntAccessor.h"
#include "uci/base/export.h"
#include "uci/type/PO_WindowID_Type.h"

/** The namespace in which all UCI data types are declared */
namespace uci {

/** The namespace in which all base data types are declared */
namespace base {

class AbstractServiceBusConnection;

} // namespace base
} // namespace uci

/** The namespace in which all UCI data types are declared */
namespace uci {

/** The namespace in which all generated data types are declared */
namespace type {

/** See annotations in child elements and messages/elements that use this type for details. */
class PO_ComponentWindowType : public virtual uci::base::Accessor {
public:

  /** This method constructs a new PO_ComponentWindowType.
    *
    * @param abstractServiceBusConnection The pointer to the Abstract Service Bus Connection that provides the support
    *      required to create objects.
    * @return The newly contructed PO_ComponentWindowType.
    */
  static UCI_EXPORT PO_ComponentWindowType& create(uci::base::AbstractServiceBusConnection* abstractServiceBusConnection = NULL);

  /** This method constructs a new PO_ComponentWindowType initializing the data accessed by the new PO_ComponentWindowType
    * using the data accessed by the specified PO_ComponentWindowType (cloning).
    *
    * @param accessor The PO_ComponentWindowType that provides access to the data that is to be used to initialize the data
    *      accessed by the new created PO_ComponentWindowType.
    * @param abstractServiceBusConnection The pointer to the Abstract Service Bus Connection that provides the support
    *      required to create objects.
    * @return The newly contructed PO_ComponentWindowType.
    */
  static UCI_EXPORT PO_ComponentWindowType& create(const PO_ComponentWindowType& accessor, uci::base::AbstractServiceBusConnection* abstractServiceBusConnection = NULL);

  /** This method destroys the specified PO_ComponentWindowType. Use of the specified accessor after it has been destroyed
    * will result in undefined behavior.
    *
    * @param accessor The PO_ComponentWindowType that is to be destroyed.
    */
  static UCI_EXPORT void destroy(PO_ComponentWindowType& accessor);

  /** Returns this accessor's type constant, i.e. pO_ComponentWindowType.
    *
    * @return This accessor's type constant, i.e. pO_ComponentWindowType.
    */
  virtual uci::base::accessorType::AccessorType getAccessorType() const noexception {
    return uci::type::accessorType::pO_ComponentWindowType;
  }

  /** Returns the version that was initialized from the uci:version attribute of PO_ComponentWindowType.
    *
    * @return The version that was initialized from the uci:version attribute of PO_ComponentWindowType.
    */
  static std::string getUCITypeVersion() {
    return "000.000.000.000";
  }

  /** Initializes the contents of this accessor by copying the contents of the specified accessor.
    *
    * @param accessor The accessor whose contents are to be used to initialize the contents of this accessor.
    */
  virtual void copy(const PO_ComponentWindowType& accessor) = 0;

  /** Indicates the number of discrete color values in each band, e.g. 8-bit color representation will require a value of
    * 256. [Occurrences: Minimum: 0; Maximum: MAX_LENGTH]
    */
  typedef uci::base::BoundedList<uci::base::UnsignedIntAccessor, uci::base::accessorType::unsignedIntAccessor> ColorDepth;

  /** Returns a const reference to the accessor that provides access to the complex content identified by PO_WindowID.
    *
    * @return A const reference to the accessor that provides access to the complex content identified by PO_WindowID.
    */
  virtual const uci::type::PO_WindowID_Type& getPO_WindowID() const = 0;

  /** Returns a reference to the accessor that provides access to the complex content identified by PO_WindowID.
    *
    * @return A reference to the accessor that provides access to the complex content identified by PO_WindowID.
    */
  virtual uci::type::PO_WindowID_Type& getPO_WindowID() = 0;

  /** Sets the complex content identified by PO_WindowID to the contents of the complex content accessed by the specified
    * accessor.
    *
    * @param value The accessor that provides access to the complex content whose contents are to be used to set the
    *      contents of the complex content identified by PO_WindowID.
    * @return A reference to the object on which this method was called.
    */
  virtual uci::type::PO_ComponentWindowType& setPO_WindowID(const uci::type::PO_WindowID_Type& value) = 0;

  /** Returns the value of the SimplePrimitive data type identified by WindowSizeX.
    *
    * @return The value of the simple primitive data type identified by WindowSizeX.
    */
  virtual xs::UnsignedInt getWindowSizeX() const = 0;

  /** Sets the value of the SimplePrimitive data type identified by WindowSizeX.
    *
    * @param value The value to set the SimplePrimitve data type to.
    * @return A reference to the object on which this method was called.
    */
  virtual uci::type::PO_ComponentWindowType& setWindowSizeX(xs::UnsignedInt value) = 0;

  /** Returns the value of the SimplePrimitive data type identified by WindowSizeY.
    *
    * @return The value of the simple primitive data type identified by WindowSizeY.
    */
  virtual xs::UnsignedInt getWindowSizeY() const = 0;

  /** Sets the value of the SimplePrimitive data type identified by WindowSizeY.
    *
    * @param value The value to set the SimplePrimitve data type to.
    * @return A reference to the object on which this method was called.
    */
  virtual uci::type::PO_ComponentWindowType& setWindowSizeY(xs::UnsignedInt value) = 0;

  /** Returns the value of the SimplePrimitive data type identified by LowerLeftX.
    *
    * @return The value of the simple primitive data type identified by LowerLeftX.
    */
  virtual xs::UnsignedInt getLowerLeftX() const = 0;

  /** Sets the value of the SimplePrimitive data type identified by LowerLeftX.
    *
    * @param value The value to set the SimplePrimitve data type to.
    * @return A reference to the object on which this method was called.
    */
  virtual uci::type::PO_ComponentWindowType& setLowerLeftX(xs::UnsignedInt value) = 0;

  /** Returns the value of the SimplePrimitive data type identified by LowerLeftY.
    *
    * @return The value of the simple primitive data type identified by LowerLeftY.
    */
  virtual xs::UnsignedInt getLowerLeftY() const = 0;

  /** Sets the value of the SimplePrimitive data type identified by LowerLeftY.
    *
    * @param value The value to set the SimplePrimitve data type to.
    * @return A reference to the object on which this method was called.
    */
  virtual uci::type::PO_ComponentWindowType& setLowerLeftY(xs::UnsignedInt value) = 0;

  /** Returns a const reference to the bounded list identified by ColorDepth.
    *
    * @return A const reference to the bounded list identified by ColorDepth.
    */
  virtual const uci::type::PO_ComponentWindowType::ColorDepth& getColorDepth() const = 0;

  /** Returns a reference to the bounded list identified by ColorDepth.
    *
    * @return A reference to the bounded list identified by ColorDepth.
    */
  virtual uci::type::PO_ComponentWindowType::ColorDepth& getColorDepth() = 0;

  /** Sets the bounded list identified by ColorDepth.
    *
    * @param value The bounded list whose contents are to be used to set the value of the bounded list accessed by this
    *      accessor.
    * @return A reference to the object on which this method was called.
    */
  virtual uci::type::PO_ComponentWindowType& setColorDepth(const uci::type::PO_ComponentWindowType::ColorDepth& value) = 0;

protected:

  /** The constructor [only available to derived classes]. */
  PO_ComponentWindowType() {
  }

  /** The destructor [only available to derived classes]. */
  ~PO_ComponentWindowType() {
  }

  /** The copy constructor [only available to derived classes].
    *
    * @param rhs The PO_ComponentWindowType to copy from.
    */
  PO_ComponentWindowType(const PO_ComponentWindowType& rhs) {
    (void)rhs;
  }

  /** The assignment operator. Sets the contents of this PO_ComponentWindowType to the contents of the
    * PO_ComponentWindowType on the right hand side (rhs) of the assignment operator [only available to derived classes].
    *
    * @param rhs The PO_ComponentWindowType on the right hand side (rhs) of the assignment operator whose contents are used
    *      to set the contents of this PO_ComponentWindowType.
    * @return A reference to this PO_ComponentWindowType.
    */
  PO_ComponentWindowType& operator=(const PO_ComponentWindowType& rhs) {
    (void)rhs;

    return *this;
  }

};

} // namespace type
} // namespace uci

#endif // UCI_TYPE_PO_COMPONENTWINDOWTYPE_H

