/** @file VCM_DragParametersType.h
 *
 * @warning This file is automatically generated, edit at your own risk
 *
 * This file was generated on 04/01/2024 at 02:25:08 PM
 *
 * <pre>
 * Unclassified               U N C L A S S I F I E D               Unclassified
 *
 * DISTRIBUTION STATEMENT D: Distribution authorized to Department of Defense
 *    and U.S. DoD contractors only, Critical Technology, Export Controlled,
 *    26 January 2023. Other requests for this document shall be referred to
 *    AFLCMC/XA (OAMO), Wright-Patterson AFB OH 45433.
 *
 * DESTRUCTION NOTICE: Destroy by any method that will prevent disclosure of
 *    contents or reconstruction of the document.
 *
 * WARNING - This document contains technical data whose export is restricted
 *    by the Arms Export Control Act (Section 2751 of Title 22, United States
 *    Code) or the Export Control Reform Act of 2018 (Chapter 58 Sections
 *    4801-4852 of Title 50, United States Code). Violations of these export
 *    laws are subject to severe criminal penalties. Disseminate in accordance
 *    with provisions of DoD Directive 5230.25 and DoD Instruction 2040.02.
 *
 * Controlled by: USAF
 * Controlled by: AFLCMC/XA (OAMO)
 * CUI Category(ies): CTI, EXPT
 * Distribution Statement D
 * POC: Wayne Artuso, 937-713-5124
 *
 * CUI//SP-CTI/SP-EXPT
 * </pre>
 *
 */

#ifndef UCI_TYPE_VCM_DRAGPARAMETERSTYPE_H
#define UCI_TYPE_VCM_DRAGPARAMETERSTYPE_H

#include "../base/Accessor.h"
#include "../base/DoubleAccessor.h"
#include "../base/export.h"

/** The namespace in which all UCI data types are declared */
namespace uci {

/** The namespace in which all base data types are declared */
namespace base {

class AbstractServiceBusConnection;

} // namespace base
} // namespace uci

/** The namespace in which all UCI data types are declared */
namespace uci {

/** The namespace in which all generated data types are declared */
namespace type {

/** Defines drag parameters used for VCM propagation. */
class VCM_DragParametersType : public virtual uci::base::Accessor {
public:

  /** This method constructs a new VCM_DragParametersType.
    *
    * @param abstractServiceBusConnection The pointer to the Abstract Service Bus Connection that provides the support
    *      required to create objects.
    * @return The newly contructed VCM_DragParametersType.
    */
  static UCI_EXPORT VCM_DragParametersType& create(uci::base::AbstractServiceBusConnection* abstractServiceBusConnection = NULL);

  /** This method constructs a new VCM_DragParametersType initializing the data accessed by the new VCM_DragParametersType
    * using the data accessed by the specified VCM_DragParametersType (cloning).
    *
    * @param accessor The VCM_DragParametersType that provides access to the data that is to be used to initialize the data
    *      accessed by the new created VCM_DragParametersType.
    * @param abstractServiceBusConnection The pointer to the Abstract Service Bus Connection that provides the support
    *      required to create objects.
    * @return The newly contructed VCM_DragParametersType.
    */
  static UCI_EXPORT VCM_DragParametersType& create(const VCM_DragParametersType& accessor, uci::base::AbstractServiceBusConnection* abstractServiceBusConnection = NULL);

  /** This method destroys the specified VCM_DragParametersType. Use of the specified accessor after it has been destroyed
    * will result in undefined behavior.
    *
    * @param accessor The VCM_DragParametersType that is to be destroyed.
    */
  static UCI_EXPORT void destroy(VCM_DragParametersType& accessor);

  /** Returns this accessor's type constant, i.e. vCM_DragParametersType.
    *
    * @return This accessor's type constant, i.e. vCM_DragParametersType.
    */
  virtual uci::base::accessorType::AccessorType getAccessorType() const noexception {
    return uci::type::accessorType::vCM_DragParametersType;
  }

  /** Returns the version that was initialized from the uci:version attribute of VCM_DragParametersType.
    *
    * @return The version that was initialized from the uci:version attribute of VCM_DragParametersType.
    */
  static std::string getUCITypeVersion() {
    return "000.000.000.000";
  }

  /** Initializes the contents of this accessor by copying the contents of the specified accessor.
    *
    * @param accessor The accessor whose contents are to be used to initialize the contents of this accessor.
    */
  virtual void copy(const VCM_DragParametersType& accessor) = 0;

  /** Returns the value of the SimplePrimitive data type identified by BallisticCoefficient.
    *
    * @return The value of the simple primitive data type identified by BallisticCoefficient.
    */
  virtual xs::Double getBallisticCoefficient() const = 0;

  /** Sets the value of the SimplePrimitive data type identified by BallisticCoefficient.
    *
    * @param value The value to set the SimplePrimitve data type to.
    * @return A reference to the object on which this method was called.
    */
  virtual uci::type::VCM_DragParametersType& setBallisticCoefficient(xs::Double value) = 0;

  /** Returns whether the Element identified by BallisticCoefficient exists (is enabled) or not.
    *
    * @return A boolean indicating whether the Element identified by BallisticCoefficient is enabled or not.
    */
  virtual bool hasBallisticCoefficient() const = 0;

  /** Clears (disabled) the Element identified by BallisticCoefficient.
    *
    * @return A reference to the object on which this method was called.
    */
  virtual uci::type::VCM_DragParametersType& clearBallisticCoefficient() = 0;

  /** Returns the value of the SimplePrimitive data type identified by BallisticCoefficientDot.
    *
    * @return The value of the simple primitive data type identified by BallisticCoefficientDot.
    */
  virtual xs::Double getBallisticCoefficientDot() const = 0;

  /** Sets the value of the SimplePrimitive data type identified by BallisticCoefficientDot.
    *
    * @param value The value to set the SimplePrimitve data type to.
    * @return A reference to the object on which this method was called.
    */
  virtual uci::type::VCM_DragParametersType& setBallisticCoefficientDot(xs::Double value) = 0;

  /** Returns whether the Element identified by BallisticCoefficientDot exists (is enabled) or not.
    *
    * @return A boolean indicating whether the Element identified by BallisticCoefficientDot is enabled or not.
    */
  virtual bool hasBallisticCoefficientDot() const = 0;

  /** Clears (disabled) the Element identified by BallisticCoefficientDot.
    *
    * @return A reference to the object on which this method was called.
    */
  virtual uci::type::VCM_DragParametersType& clearBallisticCoefficientDot() = 0;

protected:

  /** The constructor [only available to derived classes]. */
  VCM_DragParametersType() {
  }

  /** The destructor [only available to derived classes]. */
  ~VCM_DragParametersType() {
  }

  /** The copy constructor [only available to derived classes].
    *
    * @param rhs The VCM_DragParametersType to copy from.
    */
  VCM_DragParametersType(const VCM_DragParametersType& rhs) {
    (void)rhs;
  }

  /** The assignment operator. Sets the contents of this VCM_DragParametersType to the contents of the
    * VCM_DragParametersType on the right hand side (rhs) of the assignment operator [only available to derived classes].
    *
    * @param rhs The VCM_DragParametersType on the right hand side (rhs) of the assignment operator whose contents are used
    *      to set the contents of this VCM_DragParametersType.
    * @return A reference to this VCM_DragParametersType.
    */
  VCM_DragParametersType& operator=(const VCM_DragParametersType& rhs) {
    (void)rhs;

    return *this;
  }

};

} // namespace type
} // namespace uci

#endif // UCI_TYPE_VCM_DRAGPARAMETERSTYPE_H

