/** @file Link16DataLinkNativeInfoType.cpp
 *
 * @warning This file is automatically generated, edit at your own risk
 *
 * This file was generated on 04/01/2024 at 02:25:13 PM
 *
 * <pre>
 * Unclassified               U N C L A S S I F I E D               Unclassified
 *
 * DISTRIBUTION STATEMENT D: Distribution authorized to Department of Defense
 *    and U.S. DoD contractors only, Critical Technology, Export Controlled,
 *    26 January 2023. Other requests for this document shall be referred to
 *    AFLCMC/XA (OAMO), Wright-Patterson AFB OH 45433.
 *
 * DESTRUCTION NOTICE: Destroy by any method that will prevent disclosure of
 *    contents or reconstruction of the document.
 *
 * WARNING - This document contains technical data whose export is restricted
 *    by the Arms Export Control Act (Section 2751 of Title 22, United States
 *    Code) or the Export Control Reform Act of 2018 (Chapter 58 Sections
 *    4801-4852 of Title 50, United States Code). Violations of these export
 *    laws are subject to severe criminal penalties. Disseminate in accordance
 *    with provisions of DoD Directive 5230.25 and DoD Instruction 2040.02.
 *
 * Controlled by: USAF
 * Controlled by: AFLCMC/XA (OAMO)
 * CUI Category(ies): CTI, EXPT
 * Distribution Statement D
 * POC: Wayne Artuso, 937-713-5124
 *
 * CUI//SP-CTI/SP-EXPT
 * </pre>
 *
 */

#include "asb_uci/type/Link16DataLinkNativeInfoType.h"

#include <memory>
#include <string>

#include <boost/optional/optional.hpp>
#include <boost/smart_ptr/make_unique.hpp>

#include "asb_uci/type/DataLinkNativeInfoPET.h"
#include "asb_uci/type/Link16TrackBlockType.h"
#include "asb_uci/type/Link16TrackNumberType.h"
#include "asb_uci/util/SerializationHelpers.h"
#include "uci/base/UCIException.h"
#include "uci/base/accessorType.h"
#include "uci/type/Link16DataLinkNativeInfoType.h"
#include "uci/type/Link16TrackBlockType.h"
#include "uci/type/Link16TrackNumberType.h"
#include "xs/type/simpleXmlSchemaPrimitives.h"

/**  */
namespace asb_uci {

/** The namespace in which all generated data types are declared */
namespace type {

Link16DataLinkNativeInfoType::Link16DataLinkNativeInfoType()
  : sourceTrackNumber_Accessor{boost::make_unique<Link16TrackNumberType>()},
    trackBlock_Accessor{boost::make_unique<TrackBlock>(0, SIZE_MAX)} {
}

Link16DataLinkNativeInfoType::~Link16DataLinkNativeInfoType() = default;

void Link16DataLinkNativeInfoType::copy(const uci::type::Link16DataLinkNativeInfoType& accessor) {
  copyImpl(accessor, false);
}

void Link16DataLinkNativeInfoType::copyImpl(const uci::type::Link16DataLinkNativeInfoType& accessor, const bool /*checkIfDerivation*/) {
  if (&accessor != this) {
    DataLinkNativeInfoPET::copyImpl(accessor, false);
    const auto& accessorImpl = dynamic_cast<const Link16DataLinkNativeInfoType&>(accessor);
    setSourceTrackNumber(*(accessorImpl.sourceTrackNumber_Accessor));
    setC2Indicator(accessorImpl.c2Indicator_Accessor);
    setCDO_Authority(accessorImpl.cDO_Authority_Accessor);
    setTrackBlock(*(accessorImpl.trackBlock_Accessor));
  }
}

void Link16DataLinkNativeInfoType::reset() noexcept {
  DataLinkNativeInfoPET::reset();
  sourceTrackNumber_Accessor->reset();
  c2Indicator_Accessor = false;
  cDO_Authority_Accessor = false;
  trackBlock_Accessor->reset();
}

const uci::type::Link16TrackNumberType& Link16DataLinkNativeInfoType::getSourceTrackNumber() const noexcept {
  return *sourceTrackNumber_Accessor;
}

uci::type::Link16TrackNumberType& Link16DataLinkNativeInfoType::getSourceTrackNumber() noexcept {
  return *sourceTrackNumber_Accessor;
}

uci::type::Link16DataLinkNativeInfoType& Link16DataLinkNativeInfoType::setSourceTrackNumber(const uci::type::Link16TrackNumberType& value) {
  return setSourceTrackNumber(value.c_str());
}

uci::type::Link16DataLinkNativeInfoType& Link16DataLinkNativeInfoType::setSourceTrackNumber(const std::string& value) {
  return setSourceTrackNumber(value.c_str());
}

uci::type::Link16DataLinkNativeInfoType& Link16DataLinkNativeInfoType::setSourceTrackNumber(const char* value) {
  sourceTrackNumber_Accessor->setStringValue(value);
  return *this;
}

xs::Boolean Link16DataLinkNativeInfoType::getC2Indicator() const {
  return c2Indicator_Accessor;
}

uci::type::Link16DataLinkNativeInfoType& Link16DataLinkNativeInfoType::setC2Indicator(xs::Boolean value) {
  c2Indicator_Accessor = value;
  return *this;
}


xs::Boolean Link16DataLinkNativeInfoType::getCDO_Authority() const {
  return cDO_Authority_Accessor;
}

uci::type::Link16DataLinkNativeInfoType& Link16DataLinkNativeInfoType::setCDO_Authority(xs::Boolean value) {
  cDO_Authority_Accessor = value;
  return *this;
}


const uci::type::Link16DataLinkNativeInfoType::TrackBlock& Link16DataLinkNativeInfoType::getTrackBlock() const {
  return *trackBlock_Accessor;
}

uci::type::Link16DataLinkNativeInfoType::TrackBlock& Link16DataLinkNativeInfoType::getTrackBlock() {
  return *trackBlock_Accessor;
}

uci::type::Link16DataLinkNativeInfoType& Link16DataLinkNativeInfoType::setTrackBlock(const uci::type::Link16DataLinkNativeInfoType::TrackBlock& accessor) {
  if (&accessor != trackBlock_Accessor.get()) {
    trackBlock_Accessor->copyImpl(accessor, false);
  }
  return *this;
}

std::unique_ptr<Link16DataLinkNativeInfoType> Link16DataLinkNativeInfoType::create(const uci::base::accessorType::AccessorType type) {
  const uci::base::accessorType::AccessorType requestedType{(type == uci::base::accessorType::null) ? uci::type::accessorType::link16DataLinkNativeInfoType : type};
  return (requestedType == uci::type::accessorType::link16DataLinkNativeInfoType) ? boost::make_unique<Link16DataLinkNativeInfoType>() : nullptr;
}

/**  */
namespace Link16DataLinkNativeInfoType_Names {

constexpr const char* Extern_Type_Name{"Link16DataLinkNativeInfoType"};
constexpr const char* SourceTrackNumber_Name{"SourceTrackNumber"};
constexpr const char* C2Indicator_Name{"C2Indicator"};
constexpr const char* CDO_Authority_Name{"CDO_Authority"};
constexpr const char* TrackBlock_Name{"TrackBlock"};

} // namespace Link16DataLinkNativeInfoType_Names

void Link16DataLinkNativeInfoType::deserialize(const boost::property_tree::ptree& propTree, uci::type::Link16DataLinkNativeInfoType& accessor, std::string& nodeName, std::string& nsPrefix, const bool topLevel) {
  nodeName = Link16DataLinkNativeInfoType_Names::Extern_Type_Name;
  const boost::property_tree::ptree& node = (topLevel ? propTree.ordered_begin()->second : propTree);
  for (const boost::property_tree::ptree::value_type& valueType : node.get_child("")) {
    if ((valueType.first == "<xmlattr>") && topLevel) {
      nsPrefix = asb_uci::util::SerializationHelpers::checkForNamespacePrefix(valueType.second.get_child(""));
    } else if (valueType.first == nsPrefix + Link16DataLinkNativeInfoType_Names::SourceTrackNumber_Name) {
      if (const boost::optional<std::string> value = valueType.second.get_value_optional<std::string>()) {
        accessor.setSourceTrackNumber(*value);
      }
    } else if (valueType.first == nsPrefix + Link16DataLinkNativeInfoType_Names::C2Indicator_Name) {
      if (const boost::optional<std::string> value = valueType.second.get_value_optional<std::string>()) {
        accessor.setC2Indicator(asb_uci::util::SerializationHelpers::deserializeBoolean(*value));
      }
    } else if (valueType.first == nsPrefix + Link16DataLinkNativeInfoType_Names::CDO_Authority_Name) {
      if (const boost::optional<std::string> value = valueType.second.get_value_optional<std::string>()) {
        accessor.setCDO_Authority(asb_uci::util::SerializationHelpers::deserializeBoolean(*value));
      }
    } else if (valueType.first == nsPrefix + Link16DataLinkNativeInfoType_Names::TrackBlock_Name) {
      if (const boost::optional<std::string> value = valueType.second.get_value_optional<std::string>()) {
        uci::type::Link16DataLinkNativeInfoType::TrackBlock& boundedList = accessor.getTrackBlock();
        const uci::type::Link16DataLinkNativeInfoType::TrackBlock::size_type boundedListSize{boundedList.size()};
        boundedList.resize(boundedListSize + 1);
        asb_uci::type::Link16TrackBlockType::deserialize(valueType.second, boundedList.at(boundedListSize), nodeName, nsPrefix);
      }
    }
  }
  DataLinkNativeInfoPET::deserialize(node, accessor, nodeName, nsPrefix);
}

std::string Link16DataLinkNativeInfoType::serialize(const uci::type::Link16DataLinkNativeInfoType& accessor, boost::property_tree::ptree& propTree, const std::string& nodeName, const bool createNode, const bool addTypeAttribute, const bool /*checkIfDerivation*/, const bool /*topLevel*/) {
  std::string generatedNodeName{(nodeName.empty() ? Link16DataLinkNativeInfoType_Names::Extern_Type_Name : nodeName)};
  boost::property_tree::ptree newNode;
  boost::property_tree::ptree& node = (createNode ? newNode : propTree);
  if (addTypeAttribute) {
    asb_uci::util::SerializationHelpers::addTypeAttribute(node, Link16DataLinkNativeInfoType_Names::Extern_Type_Name);
  }
  DataLinkNativeInfoPET::serialize(accessor, node, "", false, false, false);
  asb_uci::util::SerializationHelpers::serializeString(accessor.getSourceTrackNumber(), node, Link16DataLinkNativeInfoType_Names::SourceTrackNumber_Name);
  asb_uci::util::SerializationHelpers::serializeBoolean(accessor.getC2Indicator(), node, Link16DataLinkNativeInfoType_Names::C2Indicator_Name);
  asb_uci::util::SerializationHelpers::serializeBoolean(accessor.getCDO_Authority(), node, Link16DataLinkNativeInfoType_Names::CDO_Authority_Name);
  {
    const uci::type::Link16DataLinkNativeInfoType::TrackBlock& boundedList = accessor.getTrackBlock();
    for (uci::type::Link16DataLinkNativeInfoType::TrackBlock::size_type i = 0, end = boundedList.size(); i < end; ++i) {
      asb_uci::type::Link16TrackBlockType::serialize(boundedList.at(i), node, Link16DataLinkNativeInfoType_Names::TrackBlock_Name);
    }
  }
  if (createNode) {
    propTree.add_child(generatedNodeName, node);
  }
  return generatedNodeName;
}

} // namespace type

} // namespace asb_uci

/** The namespace in which all UCI data types are declared */
namespace uci {

/** The namespace in which all generated data types are declared */
namespace type {

uci::type::Link16DataLinkNativeInfoType& Link16DataLinkNativeInfoType::create(uci::base::AbstractServiceBusConnection* /*abstractServiceBusConnection*/) {
  return *(boost::make_unique<asb_uci::type::Link16DataLinkNativeInfoType>().release());
}

uci::type::Link16DataLinkNativeInfoType& Link16DataLinkNativeInfoType::create(const uci::type::Link16DataLinkNativeInfoType& accessor, uci::base::AbstractServiceBusConnection* /*abstractServiceBusConnection*/) {
  std::unique_ptr<asb_uci::type::Link16DataLinkNativeInfoType> newAccessor{boost::make_unique<asb_uci::type::Link16DataLinkNativeInfoType>()};
  newAccessor->copyImpl(accessor, false);
  return *(newAccessor.release());
}

void Link16DataLinkNativeInfoType::destroy(uci::type::Link16DataLinkNativeInfoType& accessor) {
  delete dynamic_cast<asb_uci::type::Link16DataLinkNativeInfoType*>(&accessor);
}

} // namespace type

} // namespace uci

