/** @file MessageTransmissionFilterRecordDRLE.cpp
 *
 * @warning This file is automatically generated, edit at your own risk
 *
 * This file was generated on 04/01/2024 at 02:25:13 PM
 *
 * <pre>
 * Unclassified               U N C L A S S I F I E D               Unclassified
 *
 * DISTRIBUTION STATEMENT D: Distribution authorized to Department of Defense
 *    and U.S. DoD contractors only, Critical Technology, Export Controlled,
 *    26 January 2023. Other requests for this document shall be referred to
 *    AFLCMC/XA (OAMO), Wright-Patterson AFB OH 45433.
 *
 * DESTRUCTION NOTICE: Destroy by any method that will prevent disclosure of
 *    contents or reconstruction of the document.
 *
 * WARNING - This document contains technical data whose export is restricted
 *    by the Arms Export Control Act (Section 2751 of Title 22, United States
 *    Code) or the Export Control Reform Act of 2018 (Chapter 58 Sections
 *    4801-4852 of Title 50, United States Code). Violations of these export
 *    laws are subject to severe criminal penalties. Disseminate in accordance
 *    with provisions of DoD Directive 5230.25 and DoD Instruction 2040.02.
 *
 * Controlled by: USAF
 * Controlled by: AFLCMC/XA (OAMO)
 * CUI Category(ies): CTI, EXPT
 * Distribution Statement D
 * POC: Wayne Artuso, 937-713-5124
 *
 * CUI//SP-CTI/SP-EXPT
 * </pre>
 *
 */

#include "../../../include/asb_uci/type/MessageTransmissionFilterRecordDRLE.h"

#include <memory>
#include <string>

#include <boost/optional/optional.hpp>
#include <boost/smart_ptr/make_unique.hpp>

#include "../../../include/asb_uci/type/DataRecordBaseType.h"
#include "../../../include/asb_uci/type/MessageTransmissionFilterRecordID_Type.h"
#include "../../../include/asb_uci/util/DerivedTypesCopier.h"
#include "../../../include/asb_uci/util/DerivedTypesCreator.h"
#include "../../../include/asb_uci/util/DerivedTypesDeserializer.h"
#include "../../../include/asb_uci/util/DerivedTypesSerializer.h"
#include "../../../include/asb_uci/util/SerializationHelpers.h"
#include "../../../../cppInterface/2.3.2/include/uci/base/UCIException.h"
#include "../../../../cppInterface/2.3.2/include/uci/base/accessorType.h"
#include "../../../../cppInterface/2.3.2/include/uci/type/MessageTransmissionFilterRecordDRLE.h"
#include "../../../../cppInterface/2.3.2/include/uci/type/MessageTransmissionFilterRecordID_Type.h"

/**  */
namespace asb_uci {

/** The namespace in which all generated data types are declared */
namespace type {

MessageTransmissionFilterRecordDRLE::MessageTransmissionFilterRecordDRLE()
  : messageTransmissionFilterRecordID_Accessor{boost::make_unique<MessageTransmissionFilterRecordID_Type>()} {
}

MessageTransmissionFilterRecordDRLE::~MessageTransmissionFilterRecordDRLE() = default;

void MessageTransmissionFilterRecordDRLE::copy(const uci::type::MessageTransmissionFilterRecordDRLE& accessor) {
  copyImpl(accessor, false);
}

void MessageTransmissionFilterRecordDRLE::copyImpl(const uci::type::MessageTransmissionFilterRecordDRLE& accessor, const bool checkIfDerivation) {
  if (&accessor != this) {
    if (!checkIfDerivation || (accessor.getAccessorType() == uci::type::accessorType::messageTransmissionFilterRecordDRLE)) {
      DataRecordBaseType::copyImpl(accessor, false);
      const auto& accessorImpl = dynamic_cast<const MessageTransmissionFilterRecordDRLE&>(accessor);
      setMessageTransmissionFilterRecordID(*(accessorImpl.messageTransmissionFilterRecordID_Accessor));
    } else {
      asb_uci::util::DerivedTypesCopier::copy(accessor, *this);
    }
  }
}

void MessageTransmissionFilterRecordDRLE::reset() noexcept {
  DataRecordBaseType::reset();
  messageTransmissionFilterRecordID_Accessor->reset();
}

const uci::type::MessageTransmissionFilterRecordID_Type& MessageTransmissionFilterRecordDRLE::getMessageTransmissionFilterRecordID() const {
  return *messageTransmissionFilterRecordID_Accessor;
}

uci::type::MessageTransmissionFilterRecordID_Type& MessageTransmissionFilterRecordDRLE::getMessageTransmissionFilterRecordID() {
  return *messageTransmissionFilterRecordID_Accessor;
}

uci::type::MessageTransmissionFilterRecordDRLE& MessageTransmissionFilterRecordDRLE::setMessageTransmissionFilterRecordID(const uci::type::MessageTransmissionFilterRecordID_Type& accessor) {
  if (&accessor != messageTransmissionFilterRecordID_Accessor.get()) {
    messageTransmissionFilterRecordID_Accessor->copyImpl(accessor, false);
  }
  return *this;
}

std::unique_ptr<MessageTransmissionFilterRecordDRLE> MessageTransmissionFilterRecordDRLE::create(const uci::base::accessorType::AccessorType type) {
  const uci::base::accessorType::AccessorType requestedType{(type == uci::base::accessorType::null) ? uci::type::accessorType::messageTransmissionFilterRecordDRLE : type};
  return std::unique_ptr<MessageTransmissionFilterRecordDRLE>(dynamic_cast<MessageTransmissionFilterRecordDRLE*>(asb_uci::util::DerivedTypesCreator::create(requestedType)));
}

/**  */
namespace MessageTransmissionFilterRecordDRLE_Names {

constexpr const char* Extern_Type_Name{"MessageTransmissionFilterRecordDRLE"};
constexpr const char* MessageTransmissionFilterRecordID_Name{"MessageTransmissionFilterRecordID"};

} // namespace MessageTransmissionFilterRecordDRLE_Names

void MessageTransmissionFilterRecordDRLE::deserialize(const boost::property_tree::ptree& propTree, uci::type::MessageTransmissionFilterRecordDRLE& accessor, std::string& nodeName, std::string& nsPrefix, const bool topLevel) {
  nodeName = MessageTransmissionFilterRecordDRLE_Names::Extern_Type_Name;
  const boost::property_tree::ptree& node = (topLevel ? propTree.ordered_begin()->second : propTree);
  for (const boost::property_tree::ptree::value_type& valueType : node.get_child("")) {
    if ((valueType.first == "<xmlattr>") && topLevel) {
      nsPrefix = asb_uci::util::SerializationHelpers::checkForNamespacePrefix(valueType.second.get_child(""));
    } else if (valueType.first == nsPrefix + MessageTransmissionFilterRecordDRLE_Names::MessageTransmissionFilterRecordID_Name) {
      MessageTransmissionFilterRecordID_Type::deserialize(valueType.second, accessor.getMessageTransmissionFilterRecordID(), nodeName, nsPrefix);
    }
  }
  DataRecordBaseType::deserialize(node, accessor, nodeName, nsPrefix);
}

std::string MessageTransmissionFilterRecordDRLE::serialize(const uci::type::MessageTransmissionFilterRecordDRLE& accessor, boost::property_tree::ptree& propTree, const std::string& nodeName, const bool createNode, const bool addTypeAttribute, const bool checkIfDerivation, const bool /*topLevel*/) {
  std::string generatedNodeName{(nodeName.empty() ? MessageTransmissionFilterRecordDRLE_Names::Extern_Type_Name : nodeName)};
  if (!checkIfDerivation || (accessor.getAccessorType() == uci::type::accessorType::messageTransmissionFilterRecordDRLE)) {
    boost::property_tree::ptree newNode;
    boost::property_tree::ptree& node = (createNode ? newNode : propTree);
    if (addTypeAttribute) {
      asb_uci::util::SerializationHelpers::addTypeAttribute(node, MessageTransmissionFilterRecordDRLE_Names::Extern_Type_Name);
    }
    DataRecordBaseType::serialize(accessor, node, "", false, false, false);
    MessageTransmissionFilterRecordID_Type::serialize(accessor.getMessageTransmissionFilterRecordID(), node, MessageTransmissionFilterRecordDRLE_Names::MessageTransmissionFilterRecordID_Name);
    if (createNode) {
      propTree.add_child(generatedNodeName, node);
    }
  } else {
    asb_uci::util::DerivedTypesSerializer::serialize(accessor, propTree, nodeName, createNode);
  }
  return generatedNodeName;
}

} // namespace type

} // namespace asb_uci

/** The namespace in which all UCI data types are declared */
namespace uci {

/** The namespace in which all generated data types are declared */
namespace type {

uci::type::MessageTransmissionFilterRecordDRLE& MessageTransmissionFilterRecordDRLE::create(uci::base::AbstractServiceBusConnection* /*abstractServiceBusConnection*/) {
  return *(boost::make_unique<asb_uci::type::MessageTransmissionFilterRecordDRLE>().release());
}

uci::type::MessageTransmissionFilterRecordDRLE& MessageTransmissionFilterRecordDRLE::create(const uci::type::MessageTransmissionFilterRecordDRLE& accessor, uci::base::AbstractServiceBusConnection* /*abstractServiceBusConnection*/) {
  std::unique_ptr<asb_uci::type::MessageTransmissionFilterRecordDRLE> newAccessor{boost::make_unique<asb_uci::type::MessageTransmissionFilterRecordDRLE>()};
  newAccessor->copyImpl(accessor, false);
  return *(newAccessor.release());
}

void MessageTransmissionFilterRecordDRLE::destroy(uci::type::MessageTransmissionFilterRecordDRLE& accessor) {
  delete dynamic_cast<asb_uci::type::MessageTransmissionFilterRecordDRLE*>(&accessor);
}

} // namespace type

} // namespace uci

