/** @file MissionRequirementStatusType.cpp
 *
 * @warning This file is automatically generated, edit at your own risk
 *
 * This file was generated on 04/01/2024 at 02:25:13 PM
 *
 * <pre>
 * Unclassified               U N C L A S S I F I E D               Unclassified
 *
 * DISTRIBUTION STATEMENT D: Distribution authorized to Department of Defense
 *    and U.S. DoD contractors only, Critical Technology, Export Controlled,
 *    26 January 2023. Other requests for this document shall be referred to
 *    AFLCMC/XA (OAMO), Wright-Patterson AFB OH 45433.
 *
 * DESTRUCTION NOTICE: Destroy by any method that will prevent disclosure of
 *    contents or reconstruction of the document.
 *
 * WARNING - This document contains technical data whose export is restricted
 *    by the Arms Export Control Act (Section 2751 of Title 22, United States
 *    Code) or the Export Control Reform Act of 2018 (Chapter 58 Sections
 *    4801-4852 of Title 50, United States Code). Violations of these export
 *    laws are subject to severe criminal penalties. Disseminate in accordance
 *    with provisions of DoD Directive 5230.25 and DoD Instruction 2040.02.
 *
 * Controlled by: USAF
 * Controlled by: AFLCMC/XA (OAMO)
 * CUI Category(ies): CTI, EXPT
 * Distribution Statement D
 * POC: Wayne Artuso, 937-713-5124
 *
 * CUI//SP-CTI/SP-EXPT
 * </pre>
 *
 */

#include "../../../include/asb_uci/type/MissionRequirementStatusType.h"

#include <memory>
#include <string>

#include <boost/optional/optional.hpp>
#include <boost/smart_ptr/make_unique.hpp>

#include "../../../include/asb_uci/type/MissionPlanID_Type.h"
#include "../../../include/asb_uci/type/RequirementStatusType.h"
#include "../../../include/asb_uci/util/SerializationHelpers.h"
#include "../../../../cppInterface/2.3.2/include/uci/base/UCIException.h"
#include "../../../../cppInterface/2.3.2/include/uci/base/accessorType.h"
#include "../../../../cppInterface/2.3.2/include/uci/type/MissionPlanID_Type.h"
#include "../../../../cppInterface/2.3.2/include/uci/type/MissionRequirementStatusType.h"
#include "../../../../cppInterface/2.3.2/include/uci/type/RequirementStatusType.h"

/**  */
namespace asb_uci {

/** The namespace in which all generated data types are declared */
namespace type {

MissionRequirementStatusType::MissionRequirementStatusType()
  : missionPlanID_Accessor{boost::make_unique<MissionPlanID_Type>()},
    requirementStatus_Accessor{boost::make_unique<RequirementStatus>(0, SIZE_MAX)} {
}

MissionRequirementStatusType::~MissionRequirementStatusType() = default;

void MissionRequirementStatusType::copy(const uci::type::MissionRequirementStatusType& accessor) {
  copyImpl(accessor, false);
}

void MissionRequirementStatusType::copyImpl(const uci::type::MissionRequirementStatusType& accessor, const bool /*checkIfDerivation*/) {
  if (&accessor != this) {
    const auto& accessorImpl = dynamic_cast<const MissionRequirementStatusType&>(accessor);
    setMissionPlanID(*(accessorImpl.missionPlanID_Accessor));
    setRequirementStatus(*(accessorImpl.requirementStatus_Accessor));
  }
}

void MissionRequirementStatusType::reset() noexcept {
  missionPlanID_Accessor->reset();
  requirementStatus_Accessor->reset();
}

const uci::type::MissionPlanID_Type& MissionRequirementStatusType::getMissionPlanID() const {
  return *missionPlanID_Accessor;
}

uci::type::MissionPlanID_Type& MissionRequirementStatusType::getMissionPlanID() {
  return *missionPlanID_Accessor;
}

uci::type::MissionRequirementStatusType& MissionRequirementStatusType::setMissionPlanID(const uci::type::MissionPlanID_Type& accessor) {
  if (&accessor != missionPlanID_Accessor.get()) {
    missionPlanID_Accessor->copyImpl(accessor, false);
  }
  return *this;
}

const uci::type::MissionRequirementStatusType::RequirementStatus& MissionRequirementStatusType::getRequirementStatus() const {
  return *requirementStatus_Accessor;
}

uci::type::MissionRequirementStatusType::RequirementStatus& MissionRequirementStatusType::getRequirementStatus() {
  return *requirementStatus_Accessor;
}

uci::type::MissionRequirementStatusType& MissionRequirementStatusType::setRequirementStatus(const uci::type::MissionRequirementStatusType::RequirementStatus& accessor) {
  if (&accessor != requirementStatus_Accessor.get()) {
    requirementStatus_Accessor->copyImpl(accessor, false);
  }
  return *this;
}

std::unique_ptr<MissionRequirementStatusType> MissionRequirementStatusType::create(const uci::base::accessorType::AccessorType type) {
  const uci::base::accessorType::AccessorType requestedType{(type == uci::base::accessorType::null) ? uci::type::accessorType::missionRequirementStatusType : type};
  return (requestedType == uci::type::accessorType::missionRequirementStatusType) ? boost::make_unique<MissionRequirementStatusType>() : nullptr;
}

/**  */
namespace MissionRequirementStatusType_Names {

constexpr const char* Extern_Type_Name{"MissionRequirementStatusType"};
constexpr const char* MissionPlanID_Name{"MissionPlanID"};
constexpr const char* RequirementStatus_Name{"RequirementStatus"};

} // namespace MissionRequirementStatusType_Names

void MissionRequirementStatusType::deserialize(const boost::property_tree::ptree& propTree, uci::type::MissionRequirementStatusType& accessor, std::string& nodeName, std::string& nsPrefix, const bool topLevel) {
  nodeName = MissionRequirementStatusType_Names::Extern_Type_Name;
  const boost::property_tree::ptree& node = (topLevel ? propTree.ordered_begin()->second : propTree);
  for (const boost::property_tree::ptree::value_type& valueType : node.get_child("")) {
    if ((valueType.first == "<xmlattr>") && topLevel) {
      nsPrefix = asb_uci::util::SerializationHelpers::checkForNamespacePrefix(valueType.second.get_child(""));
    } else if (valueType.first == nsPrefix + MissionRequirementStatusType_Names::MissionPlanID_Name) {
      MissionPlanID_Type::deserialize(valueType.second, accessor.getMissionPlanID(), nodeName, nsPrefix);
    } else if (valueType.first == nsPrefix + MissionRequirementStatusType_Names::RequirementStatus_Name) {
      if (const boost::optional<std::string> value = valueType.second.get_value_optional<std::string>()) {
        uci::type::MissionRequirementStatusType::RequirementStatus& boundedList = accessor.getRequirementStatus();
        const uci::type::MissionRequirementStatusType::RequirementStatus::size_type boundedListSize{boundedList.size()};
        boundedList.resize(boundedListSize + 1);
        asb_uci::type::RequirementStatusType::deserialize(valueType.second, boundedList.at(boundedListSize), nodeName, nsPrefix);
      }
    }
  }
}

std::string MissionRequirementStatusType::serialize(const uci::type::MissionRequirementStatusType& accessor, boost::property_tree::ptree& propTree, const std::string& nodeName, const bool createNode, const bool addTypeAttribute, const bool /*checkIfDerivation*/, const bool /*topLevel*/) {
  std::string generatedNodeName{(nodeName.empty() ? MissionRequirementStatusType_Names::Extern_Type_Name : nodeName)};
  boost::property_tree::ptree newNode;
  boost::property_tree::ptree& node = (createNode ? newNode : propTree);
  if (addTypeAttribute) {
    asb_uci::util::SerializationHelpers::addTypeAttribute(node, MissionRequirementStatusType_Names::Extern_Type_Name);
  }
  MissionPlanID_Type::serialize(accessor.getMissionPlanID(), node, MissionRequirementStatusType_Names::MissionPlanID_Name);
  {
    const uci::type::MissionRequirementStatusType::RequirementStatus& boundedList = accessor.getRequirementStatus();
    for (uci::type::MissionRequirementStatusType::RequirementStatus::size_type i = 0, end = boundedList.size(); i < end; ++i) {
      asb_uci::type::RequirementStatusType::serialize(boundedList.at(i), node, MissionRequirementStatusType_Names::RequirementStatus_Name);
    }
  }
  if (createNode) {
    propTree.add_child(generatedNodeName, node);
  }
  return generatedNodeName;
}

} // namespace type

} // namespace asb_uci

/** The namespace in which all UCI data types are declared */
namespace uci {

/** The namespace in which all generated data types are declared */
namespace type {

uci::type::MissionRequirementStatusType& MissionRequirementStatusType::create(uci::base::AbstractServiceBusConnection* /*abstractServiceBusConnection*/) {
  return *(boost::make_unique<asb_uci::type::MissionRequirementStatusType>().release());
}

uci::type::MissionRequirementStatusType& MissionRequirementStatusType::create(const uci::type::MissionRequirementStatusType& accessor, uci::base::AbstractServiceBusConnection* /*abstractServiceBusConnection*/) {
  std::unique_ptr<asb_uci::type::MissionRequirementStatusType> newAccessor{boost::make_unique<asb_uci::type::MissionRequirementStatusType>()};
  newAccessor->copyImpl(accessor, false);
  return *(newAccessor.release());
}

void MissionRequirementStatusType::destroy(uci::type::MissionRequirementStatusType& accessor) {
  delete dynamic_cast<asb_uci::type::MissionRequirementStatusType*>(&accessor);
}

} // namespace type

} // namespace uci

