/** @file OperatorActionCommandMDT.cpp
 *
 * @warning This file is automatically generated, edit at your own risk
 *
 * This file was generated on 04/01/2024 at 02:25:13 PM
 *
 * <pre>
 * Unclassified               U N C L A S S I F I E D               Unclassified
 *
 * DISTRIBUTION STATEMENT D: Distribution authorized to Department of Defense
 *    and U.S. DoD contractors only, Critical Technology, Export Controlled,
 *    26 January 2023. Other requests for this document shall be referred to
 *    AFLCMC/XA (OAMO), Wright-Patterson AFB OH 45433.
 *
 * DESTRUCTION NOTICE: Destroy by any method that will prevent disclosure of
 *    contents or reconstruction of the document.
 *
 * WARNING - This document contains technical data whose export is restricted
 *    by the Arms Export Control Act (Section 2751 of Title 22, United States
 *    Code) or the Export Control Reform Act of 2018 (Chapter 58 Sections
 *    4801-4852 of Title 50, United States Code). Violations of these export
 *    laws are subject to severe criminal penalties. Disseminate in accordance
 *    with provisions of DoD Directive 5230.25 and DoD Instruction 2040.02.
 *
 * Controlled by: USAF
 * Controlled by: AFLCMC/XA (OAMO)
 * CUI Category(ies): CTI, EXPT
 * Distribution Statement D
 * POC: Wayne Artuso, 937-713-5124
 *
 * CUI//SP-CTI/SP-EXPT
 * </pre>
 *
 */

#include "../../../include/asb_uci/type/OperatorActionCommandMDT.h"

#include <memory>
#include <string>

#include <boost/optional/optional.hpp>
#include <boost/smart_ptr/make_unique.hpp>

#include "../../../include/asb_uci/type/CommandBaseType.h"
#include "../../../include/asb_uci/type/OperatorActionType.h"
#include "../../../include/asb_uci/type/OperatorNotificationID_Type.h"
#include "../../../include/asb_uci/util/SerializationHelpers.h"
#include "../../../../cppInterface/2.3.2/include/uci/base/UCIException.h"
#include "../../../../cppInterface/2.3.2/include/uci/base/accessorType.h"
#include "../../../../cppInterface/2.3.2/include/uci/type/OperatorActionCommandMDT.h"
#include "../../../../cppInterface/2.3.2/include/uci/type/OperatorActionType.h"
#include "../../../../cppInterface/2.3.2/include/uci/type/OperatorNotificationID_Type.h"

/**  */
namespace asb_uci {

/** The namespace in which all generated data types are declared */
namespace type {

OperatorActionCommandMDT::OperatorActionCommandMDT()
  : operatorNotificationID_Accessor{boost::make_unique<OperatorNotificationID_Type>()},
    commandedAction_Accessor{boost::make_unique<OperatorActionType>()} {
}

OperatorActionCommandMDT::~OperatorActionCommandMDT() = default;

void OperatorActionCommandMDT::copy(const uci::type::OperatorActionCommandMDT& accessor) {
  copyImpl(accessor, false);
}

void OperatorActionCommandMDT::copyImpl(const uci::type::OperatorActionCommandMDT& accessor, const bool /*checkIfDerivation*/) {
  if (&accessor != this) {
    CommandBaseType::copyImpl(accessor, false);
    const auto& accessorImpl = dynamic_cast<const OperatorActionCommandMDT&>(accessor);
    setOperatorNotificationID(*(accessorImpl.operatorNotificationID_Accessor));
    setCommandedAction(*(accessorImpl.commandedAction_Accessor));
  }
}

void OperatorActionCommandMDT::reset() noexcept {
  CommandBaseType::reset();
  operatorNotificationID_Accessor->reset();
  commandedAction_Accessor->reset();
}

const uci::type::OperatorNotificationID_Type& OperatorActionCommandMDT::getOperatorNotificationID() const {
  return *operatorNotificationID_Accessor;
}

uci::type::OperatorNotificationID_Type& OperatorActionCommandMDT::getOperatorNotificationID() {
  return *operatorNotificationID_Accessor;
}

uci::type::OperatorActionCommandMDT& OperatorActionCommandMDT::setOperatorNotificationID(const uci::type::OperatorNotificationID_Type& accessor) {
  if (&accessor != operatorNotificationID_Accessor.get()) {
    operatorNotificationID_Accessor->copyImpl(accessor, false);
  }
  return *this;
}

const uci::type::OperatorActionType& OperatorActionCommandMDT::getCommandedAction() const {
  return *commandedAction_Accessor;
}

uci::type::OperatorActionType& OperatorActionCommandMDT::getCommandedAction() {
  return *commandedAction_Accessor;
}

uci::type::OperatorActionCommandMDT& OperatorActionCommandMDT::setCommandedAction(const uci::type::OperatorActionType& accessor) {
  if (&accessor != commandedAction_Accessor.get()) {
    commandedAction_Accessor->copyImpl(accessor, false);
  }
  return *this;
}

std::unique_ptr<OperatorActionCommandMDT> OperatorActionCommandMDT::create(const uci::base::accessorType::AccessorType type) {
  const uci::base::accessorType::AccessorType requestedType{(type == uci::base::accessorType::null) ? uci::type::accessorType::operatorActionCommandMDT : type};
  return (requestedType == uci::type::accessorType::operatorActionCommandMDT) ? boost::make_unique<OperatorActionCommandMDT>() : nullptr;
}

/**  */
namespace OperatorActionCommandMDT_Names {

constexpr const char* Extern_Type_Name{"OperatorActionCommandMDT"};
constexpr const char* OperatorNotificationID_Name{"OperatorNotificationID"};
constexpr const char* CommandedAction_Name{"CommandedAction"};

} // namespace OperatorActionCommandMDT_Names

void OperatorActionCommandMDT::deserialize(const boost::property_tree::ptree& propTree, uci::type::OperatorActionCommandMDT& accessor, std::string& nodeName, std::string& nsPrefix, const bool topLevel) {
  nodeName = OperatorActionCommandMDT_Names::Extern_Type_Name;
  const boost::property_tree::ptree& node = (topLevel ? propTree.ordered_begin()->second : propTree);
  for (const boost::property_tree::ptree::value_type& valueType : node.get_child("")) {
    if ((valueType.first == "<xmlattr>") && topLevel) {
      nsPrefix = asb_uci::util::SerializationHelpers::checkForNamespacePrefix(valueType.second.get_child(""));
    } else if (valueType.first == nsPrefix + OperatorActionCommandMDT_Names::OperatorNotificationID_Name) {
      OperatorNotificationID_Type::deserialize(valueType.second, accessor.getOperatorNotificationID(), nodeName, nsPrefix);
    } else if (valueType.first == nsPrefix + OperatorActionCommandMDT_Names::CommandedAction_Name) {
      OperatorActionType::deserialize(valueType.second, accessor.getCommandedAction(), nodeName, nsPrefix);
    }
  }
  CommandBaseType::deserialize(node, accessor, nodeName, nsPrefix);
}

std::string OperatorActionCommandMDT::serialize(const uci::type::OperatorActionCommandMDT& accessor, boost::property_tree::ptree& propTree, const std::string& nodeName, const bool createNode, const bool addTypeAttribute, const bool /*checkIfDerivation*/, const bool /*topLevel*/) {
  std::string generatedNodeName{(nodeName.empty() ? OperatorActionCommandMDT_Names::Extern_Type_Name : nodeName)};
  boost::property_tree::ptree newNode;
  boost::property_tree::ptree& node = (createNode ? newNode : propTree);
  if (addTypeAttribute) {
    asb_uci::util::SerializationHelpers::addTypeAttribute(node, OperatorActionCommandMDT_Names::Extern_Type_Name);
  }
  CommandBaseType::serialize(accessor, node, "", false, false, false);
  OperatorNotificationID_Type::serialize(accessor.getOperatorNotificationID(), node, OperatorActionCommandMDT_Names::OperatorNotificationID_Name);
  OperatorActionType::serialize(accessor.getCommandedAction(), node, OperatorActionCommandMDT_Names::CommandedAction_Name);
  if (createNode) {
    propTree.add_child(generatedNodeName, node);
  }
  return generatedNodeName;
}

} // namespace type

} // namespace asb_uci

/** The namespace in which all UCI data types are declared */
namespace uci {

/** The namespace in which all generated data types are declared */
namespace type {

uci::type::OperatorActionCommandMDT& OperatorActionCommandMDT::create(uci::base::AbstractServiceBusConnection* /*abstractServiceBusConnection*/) {
  return *(boost::make_unique<asb_uci::type::OperatorActionCommandMDT>().release());
}

uci::type::OperatorActionCommandMDT& OperatorActionCommandMDT::create(const uci::type::OperatorActionCommandMDT& accessor, uci::base::AbstractServiceBusConnection* /*abstractServiceBusConnection*/) {
  std::unique_ptr<asb_uci::type::OperatorActionCommandMDT> newAccessor{boost::make_unique<asb_uci::type::OperatorActionCommandMDT>()};
  newAccessor->copyImpl(accessor, false);
  return *(newAccessor.release());
}

void OperatorActionCommandMDT::destroy(uci::type::OperatorActionCommandMDT& accessor) {
  delete dynamic_cast<asb_uci::type::OperatorActionCommandMDT*>(&accessor);
}

} // namespace type

} // namespace uci

