/** @file RequirementAllocationDetailsType.cpp
 *
 * @warning This file is automatically generated, edit at your own risk
 *
 * This file was generated on 04/01/2024 at 02:25:14 PM
 *
 * <pre>
 * Unclassified               U N C L A S S I F I E D               Unclassified
 *
 * DISTRIBUTION STATEMENT D: Distribution authorized to Department of Defense
 *    and U.S. DoD contractors only, Critical Technology, Export Controlled,
 *    26 January 2023. Other requests for this document shall be referred to
 *    AFLCMC/XA (OAMO), Wright-Patterson AFB OH 45433.
 *
 * DESTRUCTION NOTICE: Destroy by any method that will prevent disclosure of
 *    contents or reconstruction of the document.
 *
 * WARNING - This document contains technical data whose export is restricted
 *    by the Arms Export Control Act (Section 2751 of Title 22, United States
 *    Code) or the Export Control Reform Act of 2018 (Chapter 58 Sections
 *    4801-4852 of Title 50, United States Code). Violations of these export
 *    laws are subject to severe criminal penalties. Disseminate in accordance
 *    with provisions of DoD Directive 5230.25 and DoD Instruction 2040.02.
 *
 * Controlled by: USAF
 * Controlled by: AFLCMC/XA (OAMO)
 * CUI Category(ies): CTI, EXPT
 * Distribution Statement D
 * POC: Wayne Artuso, 937-713-5124
 *
 * CUI//SP-CTI/SP-EXPT
 * </pre>
 *
 */

#include "../../../include/asb_uci/type/RequirementAllocationDetailsType.h"

#include <memory>
#include <string>

#include <boost/optional/optional.hpp>
#include <boost/smart_ptr/make_unique.hpp>

#include "../../../include/asb_uci/type/AO_CodeType.h"
#include "../../../include/asb_uci/type/DMPI_AllocationType.h"
#include "../../../include/asb_uci/util/SerializationHelpers.h"
#include "../../../../cppInterface/2.3.2/include/uci/base/UCIException.h"
#include "../../../../cppInterface/2.3.2/include/uci/base/accessorType.h"
#include "../../../../cppInterface/2.3.2/include/uci/type/AO_CodeType.h"
#include "../../../../cppInterface/2.3.2/include/uci/type/DMPI_AllocationType.h"
#include "../../../../cppInterface/2.3.2/include/uci/type/RequirementAllocationDetailsType.h"

/**  */
namespace asb_uci {

/** The namespace in which all generated data types are declared */
namespace type {

RequirementAllocationDetailsType::RequirementAllocationDetailsType()
  : requiredDMPI_Accessor{boost::make_unique<RequiredDMPI>(0, SIZE_MAX)} {
}

RequirementAllocationDetailsType::~RequirementAllocationDetailsType() = default;

void RequirementAllocationDetailsType::copy(const uci::type::RequirementAllocationDetailsType& accessor) {
  copyImpl(accessor, false);
}

void RequirementAllocationDetailsType::copyImpl(const uci::type::RequirementAllocationDetailsType& accessor, const bool /*checkIfDerivation*/) {
  if (&accessor != this) {
    const auto& accessorImpl = dynamic_cast<const RequirementAllocationDetailsType&>(accessor);
    setRequiredDMPI(*(accessorImpl.requiredDMPI_Accessor));
    if (accessorImpl.requiredAO_Code_Accessor) {
      setRequiredAO_Code(*(accessorImpl.requiredAO_Code_Accessor));
    } else {
      requiredAO_Code_Accessor.reset();
    }
  }
}

void RequirementAllocationDetailsType::reset() noexcept {
  requiredDMPI_Accessor->reset();
  requiredAO_Code_Accessor.reset();
}

const uci::type::RequirementAllocationDetailsType::RequiredDMPI& RequirementAllocationDetailsType::getRequiredDMPI() const {
  return *requiredDMPI_Accessor;
}

uci::type::RequirementAllocationDetailsType::RequiredDMPI& RequirementAllocationDetailsType::getRequiredDMPI() {
  return *requiredDMPI_Accessor;
}

uci::type::RequirementAllocationDetailsType& RequirementAllocationDetailsType::setRequiredDMPI(const uci::type::RequirementAllocationDetailsType::RequiredDMPI& accessor) {
  if (&accessor != requiredDMPI_Accessor.get()) {
    requiredDMPI_Accessor->copyImpl(accessor, false);
  }
  return *this;
}

uci::type::AO_CodeType& RequirementAllocationDetailsType::getRequiredAO_Code_() const {
  if (requiredAO_Code_Accessor) {
    return *requiredAO_Code_Accessor;
  }
  throw uci::base::UCIException("Error in getRequiredAO_Code(): An attempt was made to get an optional field that was not enabled, call hasRequiredAO_Code() to determine if it is safe to call getRequiredAO_Code()");
}

const uci::type::AO_CodeType& RequirementAllocationDetailsType::getRequiredAO_Code() const {
  return getRequiredAO_Code_();
}

uci::type::AO_CodeType& RequirementAllocationDetailsType::getRequiredAO_Code() {
  return getRequiredAO_Code_();
}

uci::type::RequirementAllocationDetailsType& RequirementAllocationDetailsType::setRequiredAO_Code(const uci::type::AO_CodeType& accessor) {
  enableRequiredAO_Code();
  if (&accessor != requiredAO_Code_Accessor.get()) {
    requiredAO_Code_Accessor->copyImpl(accessor, false);
  }
  return *this;
}

bool RequirementAllocationDetailsType::hasRequiredAO_Code() const noexcept {
  return static_cast<bool>(requiredAO_Code_Accessor);
}

uci::type::AO_CodeType& RequirementAllocationDetailsType::enableRequiredAO_Code(uci::base::accessorType::AccessorType type) {
  const uci::base::accessorType::AccessorType requestedType{(type == uci::base::accessorType::null) ? uci::type::accessorType::aO_CodeType : type};
  if ((!requiredAO_Code_Accessor) || (requiredAO_Code_Accessor->getAccessorType() != requestedType)) {
    requiredAO_Code_Accessor = AO_CodeType::create(requestedType);
    if (!requiredAO_Code_Accessor) {
      throw uci::base::UCIException("Error in enableRequiredAO_Code(): Specified type is not equal to nor derived from the native type of object");
    }
  }
  return *requiredAO_Code_Accessor;
}

uci::type::RequirementAllocationDetailsType& RequirementAllocationDetailsType::clearRequiredAO_Code() noexcept {
  requiredAO_Code_Accessor.reset();
  return *this;
}

std::unique_ptr<RequirementAllocationDetailsType> RequirementAllocationDetailsType::create(const uci::base::accessorType::AccessorType type) {
  const uci::base::accessorType::AccessorType requestedType{(type == uci::base::accessorType::null) ? uci::type::accessorType::requirementAllocationDetailsType : type};
  return (requestedType == uci::type::accessorType::requirementAllocationDetailsType) ? boost::make_unique<RequirementAllocationDetailsType>() : nullptr;
}

/**  */
namespace RequirementAllocationDetailsType_Names {

constexpr const char* Extern_Type_Name{"RequirementAllocationDetailsType"};
constexpr const char* RequiredDMPI_Name{"RequiredDMPI"};
constexpr const char* RequiredAO_Code_Name{"RequiredAO_Code"};

} // namespace RequirementAllocationDetailsType_Names

void RequirementAllocationDetailsType::deserialize(const boost::property_tree::ptree& propTree, uci::type::RequirementAllocationDetailsType& accessor, std::string& nodeName, std::string& nsPrefix, const bool topLevel) {
  nodeName = RequirementAllocationDetailsType_Names::Extern_Type_Name;
  const boost::property_tree::ptree& node = (topLevel ? propTree.ordered_begin()->second : propTree);
  for (const boost::property_tree::ptree::value_type& valueType : node.get_child("")) {
    if ((valueType.first == "<xmlattr>") && topLevel) {
      nsPrefix = asb_uci::util::SerializationHelpers::checkForNamespacePrefix(valueType.second.get_child(""));
    } else if (valueType.first == nsPrefix + RequirementAllocationDetailsType_Names::RequiredDMPI_Name) {
      if (const boost::optional<std::string> value = valueType.second.get_value_optional<std::string>()) {
        uci::type::RequirementAllocationDetailsType::RequiredDMPI& boundedList = accessor.getRequiredDMPI();
        const uci::type::RequirementAllocationDetailsType::RequiredDMPI::size_type boundedListSize{boundedList.size()};
        boundedList.resize(boundedListSize + 1);
        asb_uci::type::DMPI_AllocationType::deserialize(valueType.second, boundedList.at(boundedListSize), nodeName, nsPrefix);
      }
    } else if (valueType.first == nsPrefix + RequirementAllocationDetailsType_Names::RequiredAO_Code_Name) {
      AO_CodeType::deserialize(valueType.second, accessor.enableRequiredAO_Code(), nodeName, nsPrefix);
    }
  }
}

std::string RequirementAllocationDetailsType::serialize(const uci::type::RequirementAllocationDetailsType& accessor, boost::property_tree::ptree& propTree, const std::string& nodeName, const bool createNode, const bool addTypeAttribute, const bool /*checkIfDerivation*/, const bool /*topLevel*/) {
  std::string generatedNodeName{(nodeName.empty() ? RequirementAllocationDetailsType_Names::Extern_Type_Name : nodeName)};
  boost::property_tree::ptree newNode;
  boost::property_tree::ptree& node = (createNode ? newNode : propTree);
  if (addTypeAttribute) {
    asb_uci::util::SerializationHelpers::addTypeAttribute(node, RequirementAllocationDetailsType_Names::Extern_Type_Name);
  }
  {
    const uci::type::RequirementAllocationDetailsType::RequiredDMPI& boundedList = accessor.getRequiredDMPI();
    for (uci::type::RequirementAllocationDetailsType::RequiredDMPI::size_type i = 0, end = boundedList.size(); i < end; ++i) {
      asb_uci::type::DMPI_AllocationType::serialize(boundedList.at(i), node, RequirementAllocationDetailsType_Names::RequiredDMPI_Name);
    }
  }
  if (accessor.hasRequiredAO_Code()) {
    AO_CodeType::serialize(accessor.getRequiredAO_Code(), node, RequirementAllocationDetailsType_Names::RequiredAO_Code_Name);
  }
  if (createNode) {
    propTree.add_child(generatedNodeName, node);
  }
  return generatedNodeName;
}

} // namespace type

} // namespace asb_uci

/** The namespace in which all UCI data types are declared */
namespace uci {

/** The namespace in which all generated data types are declared */
namespace type {

uci::type::RequirementAllocationDetailsType& RequirementAllocationDetailsType::create(uci::base::AbstractServiceBusConnection* /*abstractServiceBusConnection*/) {
  return *(boost::make_unique<asb_uci::type::RequirementAllocationDetailsType>().release());
}

uci::type::RequirementAllocationDetailsType& RequirementAllocationDetailsType::create(const uci::type::RequirementAllocationDetailsType& accessor, uci::base::AbstractServiceBusConnection* /*abstractServiceBusConnection*/) {
  std::unique_ptr<asb_uci::type::RequirementAllocationDetailsType> newAccessor{boost::make_unique<asb_uci::type::RequirementAllocationDetailsType>()};
  newAccessor->copyImpl(accessor, false);
  return *(newAccessor.release());
}

void RequirementAllocationDetailsType::destroy(uci::type::RequirementAllocationDetailsType& accessor) {
  delete dynamic_cast<asb_uci::type::RequirementAllocationDetailsType*>(&accessor);
}

} // namespace type

} // namespace uci

