/** @file SourceLocationFilterType.cpp
 *
 * @warning This file is automatically generated, edit at your own risk
 *
 * This file was generated on 04/01/2024 at 02:25:15 PM
 *
 * <pre>
 * Unclassified               U N C L A S S I F I E D               Unclassified
 *
 * DISTRIBUTION STATEMENT D: Distribution authorized to Department of Defense
 *    and U.S. DoD contractors only, Critical Technology, Export Controlled,
 *    26 January 2023. Other requests for this document shall be referred to
 *    AFLCMC/XA (OAMO), Wright-Patterson AFB OH 45433.
 *
 * DESTRUCTION NOTICE: Destroy by any method that will prevent disclosure of
 *    contents or reconstruction of the document.
 *
 * WARNING - This document contains technical data whose export is restricted
 *    by the Arms Export Control Act (Section 2751 of Title 22, United States
 *    Code) or the Export Control Reform Act of 2018 (Chapter 58 Sections
 *    4801-4852 of Title 50, United States Code). Violations of these export
 *    laws are subject to severe criminal penalties. Disseminate in accordance
 *    with provisions of DoD Directive 5230.25 and DoD Instruction 2040.02.
 *
 * Controlled by: USAF
 * Controlled by: AFLCMC/XA (OAMO)
 * CUI Category(ies): CTI, EXPT
 * Distribution Statement D
 * POC: Wayne Artuso, 937-713-5124
 *
 * CUI//SP-CTI/SP-EXPT
 * </pre>
 *
 */

#include "../../../include/asb_uci/type/SourceLocationFilterType.h"

#include <memory>
#include <string>

#include <boost/optional/optional.hpp>
#include <boost/smart_ptr/make_unique.hpp>

#include "../../../include/asb_uci/type/LocationFilterType.h"
#include "../../../include/asb_uci/type/SystemID_Type.h"
#include "../../../include/asb_uci/util/SerializationHelpers.h"
#include "../../../../cppInterface/2.3.2/include/uci/base/UCIException.h"
#include "../../../../cppInterface/2.3.2/include/uci/base/accessorType.h"
#include "../../../../cppInterface/2.3.2/include/uci/type/LocationFilterType.h"
#include "../../../../cppInterface/2.3.2/include/uci/type/SourceLocationFilterType.h"
#include "../../../../cppInterface/2.3.2/include/uci/type/SystemID_Type.h"

/**  */
namespace asb_uci {

/** The namespace in which all generated data types are declared */
namespace type {

SourceLocationFilterType::SourceLocationFilterType()
  : location_Accessor{boost::make_unique<LocationFilterType>()},
    systemID_Accessor{boost::make_unique<SystemID_Type>()} {
}

SourceLocationFilterType::~SourceLocationFilterType() = default;

void SourceLocationFilterType::copy(const uci::type::SourceLocationFilterType& accessor) {
  copyImpl(accessor, false);
}

void SourceLocationFilterType::copyImpl(const uci::type::SourceLocationFilterType& accessor, const bool /*checkIfDerivation*/) {
  if (&accessor != this) {
    const auto& accessorImpl = dynamic_cast<const SourceLocationFilterType&>(accessor);
    setLocation(*(accessorImpl.location_Accessor));
    setSystemID(*(accessorImpl.systemID_Accessor));
  }
}

void SourceLocationFilterType::reset() noexcept {
  location_Accessor->reset();
  systemID_Accessor->reset();
}

const uci::type::LocationFilterType& SourceLocationFilterType::getLocation() const {
  return *location_Accessor;
}

uci::type::LocationFilterType& SourceLocationFilterType::getLocation() {
  return *location_Accessor;
}

uci::type::SourceLocationFilterType& SourceLocationFilterType::setLocation(const uci::type::LocationFilterType& accessor) {
  if (&accessor != location_Accessor.get()) {
    location_Accessor->copyImpl(accessor, false);
  }
  return *this;
}

const uci::type::SystemID_Type& SourceLocationFilterType::getSystemID() const {
  return *systemID_Accessor;
}

uci::type::SystemID_Type& SourceLocationFilterType::getSystemID() {
  return *systemID_Accessor;
}

uci::type::SourceLocationFilterType& SourceLocationFilterType::setSystemID(const uci::type::SystemID_Type& accessor) {
  if (&accessor != systemID_Accessor.get()) {
    systemID_Accessor->copyImpl(accessor, false);
  }
  return *this;
}

std::unique_ptr<SourceLocationFilterType> SourceLocationFilterType::create(const uci::base::accessorType::AccessorType type) {
  const uci::base::accessorType::AccessorType requestedType{(type == uci::base::accessorType::null) ? uci::type::accessorType::sourceLocationFilterType : type};
  return (requestedType == uci::type::accessorType::sourceLocationFilterType) ? boost::make_unique<SourceLocationFilterType>() : nullptr;
}

/**  */
namespace SourceLocationFilterType_Names {

constexpr const char* Extern_Type_Name{"SourceLocationFilterType"};
constexpr const char* Location_Name{"Location"};
constexpr const char* SystemID_Name{"SystemID"};

} // namespace SourceLocationFilterType_Names

void SourceLocationFilterType::deserialize(const boost::property_tree::ptree& propTree, uci::type::SourceLocationFilterType& accessor, std::string& nodeName, std::string& nsPrefix, const bool topLevel) {
  nodeName = SourceLocationFilterType_Names::Extern_Type_Name;
  const boost::property_tree::ptree& node = (topLevel ? propTree.ordered_begin()->second : propTree);
  for (const boost::property_tree::ptree::value_type& valueType : node.get_child("")) {
    if ((valueType.first == "<xmlattr>") && topLevel) {
      nsPrefix = asb_uci::util::SerializationHelpers::checkForNamespacePrefix(valueType.second.get_child(""));
    } else if (valueType.first == nsPrefix + SourceLocationFilterType_Names::Location_Name) {
      LocationFilterType::deserialize(valueType.second, accessor.getLocation(), nodeName, nsPrefix);
    } else if (valueType.first == nsPrefix + SourceLocationFilterType_Names::SystemID_Name) {
      SystemID_Type::deserialize(valueType.second, accessor.getSystemID(), nodeName, nsPrefix);
    }
  }
}

std::string SourceLocationFilterType::serialize(const uci::type::SourceLocationFilterType& accessor, boost::property_tree::ptree& propTree, const std::string& nodeName, const bool createNode, const bool addTypeAttribute, const bool /*checkIfDerivation*/, const bool /*topLevel*/) {
  std::string generatedNodeName{(nodeName.empty() ? SourceLocationFilterType_Names::Extern_Type_Name : nodeName)};
  boost::property_tree::ptree newNode;
  boost::property_tree::ptree& node = (createNode ? newNode : propTree);
  if (addTypeAttribute) {
    asb_uci::util::SerializationHelpers::addTypeAttribute(node, SourceLocationFilterType_Names::Extern_Type_Name);
  }
  LocationFilterType::serialize(accessor.getLocation(), node, SourceLocationFilterType_Names::Location_Name);
  SystemID_Type::serialize(accessor.getSystemID(), node, SourceLocationFilterType_Names::SystemID_Name);
  if (createNode) {
    propTree.add_child(generatedNodeName, node);
  }
  return generatedNodeName;
}

} // namespace type

} // namespace asb_uci

/** The namespace in which all UCI data types are declared */
namespace uci {

/** The namespace in which all generated data types are declared */
namespace type {

uci::type::SourceLocationFilterType& SourceLocationFilterType::create(uci::base::AbstractServiceBusConnection* /*abstractServiceBusConnection*/) {
  return *(boost::make_unique<asb_uci::type::SourceLocationFilterType>().release());
}

uci::type::SourceLocationFilterType& SourceLocationFilterType::create(const uci::type::SourceLocationFilterType& accessor, uci::base::AbstractServiceBusConnection* /*abstractServiceBusConnection*/) {
  std::unique_ptr<asb_uci::type::SourceLocationFilterType> newAccessor{boost::make_unique<asb_uci::type::SourceLocationFilterType>()};
  newAccessor->copyImpl(accessor, false);
  return *(newAccessor.release());
}

void SourceLocationFilterType::destroy(uci::type::SourceLocationFilterType& accessor) {
  delete dynamic_cast<asb_uci::type::SourceLocationFilterType*>(&accessor);
}

} // namespace type

} // namespace uci

