/** @file ReferenceFrameObjectToFollowType.cpp
 *
 * @warning This file is automatically generated, edit at your own risk
 *
 * This file was generated on 04/01/2024 at 02:25:19 PM
 *
 * <pre>
 * Unclassified               U N C L A S S I F I E D               Unclassified
 *
 * DISTRIBUTION STATEMENT D: Distribution authorized to Department of Defense
 *    and U.S. DoD contractors only, Critical Technology, Export Controlled,
 *    26 January 2023. Other requests for this document shall be referred to
 *    AFLCMC/XA (OAMO), Wright-Patterson AFB OH 45433.
 *
 * DESTRUCTION NOTICE: Destroy by any method that will prevent disclosure of
 *    contents or reconstruction of the document.
 *
 * WARNING - This document contains technical data whose export is restricted
 *    by the Arms Export Control Act (Section 2751 of Title 22, United States
 *    Code) or the Export Control Reform Act of 2018 (Chapter 58 Sections
 *    4801-4852 of Title 50, United States Code). Violations of these export
 *    laws are subject to severe criminal penalties. Disseminate in accordance
 *    with provisions of DoD Directive 5230.25 and DoD Instruction 2040.02.
 *
 * Controlled by: USAF
 * Controlled by: AFLCMC/XA (OAMO)
 * CUI Category(ies): CTI, EXPT
 * Distribution Statement D
 * POC: Wayne Artuso, 937-713-5124
 *
 * CUI//SP-CTI/SP-EXPT
 * </pre>
 *
 */

#include "extxml_uci/type/ReferenceFrameObjectToFollowType.h"

#include <string>

#include <boost/optional/optional.hpp>
#include <boost/property_tree/ptree.hpp>

#include "extxml_uci/type/EntityID_Type.h"
#include "extxml_uci/type/SignalReportID_Type.h"
#include "extxml_uci/type/SystemID_Type.h"
#include "extxml_uci/util/DerivedTypesDeserializer.h"
#include "extxml_uci/util/SerializationHelpers.h"
#include "uci/type/ReferenceFrameObjectToFollowType.h"

/**  */
namespace extxml_uci {

/** The namespace in which all generated data types are declared */
namespace type {

/**  */
namespace ReferenceFrameObjectToFollowType_Names {

constexpr const char* Extern_Type_Name{"ReferenceFrameObjectToFollowType"};
constexpr const char* EntityID_Name{"EntityID"};
constexpr const char* SystemID_Name{"SystemID"};
constexpr const char* SignalReportID_Name{"SignalReportID"};

} // namespace ReferenceFrameObjectToFollowType_Names

bool ReferenceFrameObjectToFollowType::deserialize(const boost::property_tree::ptree& propTree, uci::type::ReferenceFrameObjectToFollowType& accessor, std::string& nodeName, std::string& nsPrefix, const bool topLevel) {
  nodeName = ReferenceFrameObjectToFollowType_Names::Extern_Type_Name;
  const boost::property_tree::ptree& node = (topLevel ? propTree.ordered_begin()->second : propTree);
  for (const boost::property_tree::ptree::value_type& valueType : node.get_child("")) {
    if ((valueType.first == "<xmlattr>") && topLevel) {
      nsPrefix = extxml_uci::util::SerializationHelpers::checkForNamespacePrefix(valueType.second.get_child(""));
    } else if (valueType.first == nsPrefix + ReferenceFrameObjectToFollowType_Names::EntityID_Name) {
      extxml_uci::util::DerivedTypesDeserializer::deserialize(valueType.second, accessor.chooseEntityID(extxml_uci::util::SerializationHelpers::checkForTypeAttribute(valueType.second, nsPrefix)), nodeName, nsPrefix);
    } else if (valueType.first == nsPrefix + ReferenceFrameObjectToFollowType_Names::SystemID_Name) {
      SystemID_Type::deserialize(valueType.second, accessor.chooseSystemID(), nodeName, nsPrefix);
    } else if (valueType.first == nsPrefix + ReferenceFrameObjectToFollowType_Names::SignalReportID_Name) {
      SignalReportID_Type::deserialize(valueType.second, accessor.chooseSignalReportID(), nodeName, nsPrefix);
    }
  }
  return true;
}

std::string ReferenceFrameObjectToFollowType::serialize(const uci::type::ReferenceFrameObjectToFollowType& accessor, boost::property_tree::ptree& propTree, const std::string& nodeName, const bool createNode, const bool addTypeAttribute, const bool /*checkIfDerivation*/, const bool /*topLevel*/) {
  std::string generatedNodeName{nodeName.empty() ? ReferenceFrameObjectToFollowType_Names::Extern_Type_Name : nodeName};
  boost::property_tree::ptree newNode;
  boost::property_tree::ptree& node = (createNode ? newNode : propTree);
  if (addTypeAttribute) {
    extxml_uci::util::SerializationHelpers::addTypeAttribute(node, ReferenceFrameObjectToFollowType_Names::Extern_Type_Name);
  }
  if (accessor.isEntityID()) {
    EntityID_Type::serialize(accessor.getEntityID(), node, ReferenceFrameObjectToFollowType_Names::EntityID_Name);
  } else if (accessor.isSystemID()) {
    SystemID_Type::serialize(accessor.getSystemID(), node, ReferenceFrameObjectToFollowType_Names::SystemID_Name);
  } else if (accessor.isSignalReportID()) {
    SignalReportID_Type::serialize(accessor.getSignalReportID(), node, ReferenceFrameObjectToFollowType_Names::SignalReportID_Name);
  }
  if (createNode) {
    propTree.add_child(generatedNodeName, node);
  }
  return generatedNodeName;
}

} // namespace type

} // namespace extxml_uci

