/** @file TaskPlanInputsType.cpp
 *
 * @warning This file is automatically generated, edit at your own risk
 *
 * This file was generated on 04/01/2024 at 02:25:19 PM
 *
 * <pre>
 * Unclassified               U N C L A S S I F I E D               Unclassified
 *
 * DISTRIBUTION STATEMENT D: Distribution authorized to Department of Defense
 *    and U.S. DoD contractors only, Critical Technology, Export Controlled,
 *    26 January 2023. Other requests for this document shall be referred to
 *    AFLCMC/XA (OAMO), Wright-Patterson AFB OH 45433.
 *
 * DESTRUCTION NOTICE: Destroy by any method that will prevent disclosure of
 *    contents or reconstruction of the document.
 *
 * WARNING - This document contains technical data whose export is restricted
 *    by the Arms Export Control Act (Section 2751 of Title 22, United States
 *    Code) or the Export Control Reform Act of 2018 (Chapter 58 Sections
 *    4801-4852 of Title 50, United States Code). Violations of these export
 *    laws are subject to severe criminal penalties. Disseminate in accordance
 *    with provisions of DoD Directive 5230.25 and DoD Instruction 2040.02.
 *
 * Controlled by: USAF
 * Controlled by: AFLCMC/XA (OAMO)
 * CUI Category(ies): CTI, EXPT
 * Distribution Statement D
 * POC: Wayne Artuso, 937-713-5124
 *
 * CUI//SP-CTI/SP-EXPT
 * </pre>
 *
 */

#include "extxml_uci/type/TaskPlanInputsType.h"

#include <string>

#include <boost/optional/optional.hpp>
#include <boost/property_tree/ptree.hpp>

#include "extxml_uci/type/PlanInputsCoreType.h"
#include "extxml_uci/type/RequirementAssociationConstraintType.h"
#include "extxml_uci/type/RequirementPlanningCandidateType.h"
#include "extxml_uci/type/TaskAllocationType.h"
#include "extxml_uci/type/TaskPlanConstraintType.h"
#include "extxml_uci/type/TaskPlanPartsType.h"
#include "extxml_uci/util/SerializationHelpers.h"
#include "uci/type/TaskPlanInputsType.h"

/**  */
namespace extxml_uci {

/** The namespace in which all generated data types are declared */
namespace type {

/**  */
namespace TaskPlanInputsType_Names {

constexpr const char* Extern_Type_Name{"TaskPlanInputsType"};
constexpr const char* PlanningCandidate_Name{"PlanningCandidate"};
constexpr const char* ProposedTaskPlan_Name{"ProposedTaskPlan"};
constexpr const char* ProposedTask_Name{"ProposedTask"};
constexpr const char* AssociationConstraint_Name{"AssociationConstraint"};
constexpr const char* OutputPlanParts_Name{"OutputPlanParts"};

} // namespace TaskPlanInputsType_Names

bool TaskPlanInputsType::deserialize(const boost::property_tree::ptree& propTree, uci::type::TaskPlanInputsType& accessor, std::string& nodeName, std::string& nsPrefix, const bool topLevel) {
  nodeName = TaskPlanInputsType_Names::Extern_Type_Name;
  const boost::property_tree::ptree& node = (topLevel ? propTree.ordered_begin()->second : propTree);
  for (const boost::property_tree::ptree::value_type& valueType : node.get_child("")) {
    if ((valueType.first == "<xmlattr>") && topLevel) {
      nsPrefix = extxml_uci::util::SerializationHelpers::checkForNamespacePrefix(valueType.second.get_child(""));
    } else if (valueType.first == nsPrefix + TaskPlanInputsType_Names::PlanningCandidate_Name) {
      if (const boost::optional<std::string> value = valueType.second.get_value_optional<std::string>()) {
        uci::type::TaskPlanInputsType::PlanningCandidate& boundedList = accessor.getPlanningCandidate();
        const uci::type::TaskPlanInputsType::PlanningCandidate::size_type boundedListSize{boundedList.size()};
        boundedList.resize(boundedListSize + 1);
        RequirementPlanningCandidateType::deserialize(valueType.second, boundedList.at(boundedListSize), nodeName, nsPrefix);
      }
    } else if (valueType.first == nsPrefix + TaskPlanInputsType_Names::ProposedTaskPlan_Name) {
      TaskPlanConstraintType::deserialize(valueType.second, accessor.enableProposedTaskPlan(), nodeName, nsPrefix);
    } else if (valueType.first == nsPrefix + TaskPlanInputsType_Names::ProposedTask_Name) {
      if (const boost::optional<std::string> value = valueType.second.get_value_optional<std::string>()) {
        uci::type::TaskPlanInputsType::ProposedTask& boundedList = accessor.getProposedTask();
        const uci::type::TaskPlanInputsType::ProposedTask::size_type boundedListSize{boundedList.size()};
        boundedList.resize(boundedListSize + 1);
        TaskAllocationType::deserialize(valueType.second, boundedList.at(boundedListSize), nodeName, nsPrefix);
      }
    } else if (valueType.first == nsPrefix + TaskPlanInputsType_Names::AssociationConstraint_Name) {
      uci::type::TaskPlanInputsType::AssociationConstraint& boundedList = accessor.getAssociationConstraint();
      const uci::type::TaskPlanInputsType::AssociationConstraint::size_type boundedListSize{boundedList.size()};
      boundedList.resize(boundedListSize + 1);
      RequirementAssociationConstraintType::deserialize(valueType.second, boundedList.at(boundedListSize), nodeName, nsPrefix);
    } else if (valueType.first == nsPrefix + TaskPlanInputsType_Names::OutputPlanParts_Name) {
      TaskPlanPartsType::deserialize(valueType.second, accessor.enableOutputPlanParts(), nodeName, nsPrefix);
    }
  }
  PlanInputsCoreType::deserialize(node, accessor, nodeName, nsPrefix);
  return true;
}

std::string TaskPlanInputsType::serialize(const uci::type::TaskPlanInputsType& accessor, boost::property_tree::ptree& propTree, const std::string& nodeName, const bool createNode, const bool addTypeAttribute, const bool /*checkIfDerivation*/, const bool /*topLevel*/) {
  std::string generatedNodeName{nodeName.empty() ? TaskPlanInputsType_Names::Extern_Type_Name : nodeName};
  boost::property_tree::ptree newNode;
  boost::property_tree::ptree& node = (createNode ? newNode : propTree);
  if (addTypeAttribute) {
    extxml_uci::util::SerializationHelpers::addTypeAttribute(node, TaskPlanInputsType_Names::Extern_Type_Name);
  }
  PlanInputsCoreType::serialize(accessor, node, "", false, false, false);
  {
    const uci::type::TaskPlanInputsType::PlanningCandidate& boundedList = accessor.getPlanningCandidate();
    for (uci::type::TaskPlanInputsType::PlanningCandidate::size_type i = 0, end = boundedList.size(); i < end; ++i) {
      RequirementPlanningCandidateType::serialize(boundedList.at(i), node, TaskPlanInputsType_Names::PlanningCandidate_Name);
    }
  }
  if (accessor.hasProposedTaskPlan()) {
    TaskPlanConstraintType::serialize(accessor.getProposedTaskPlan(), node, TaskPlanInputsType_Names::ProposedTaskPlan_Name);
  }
  {
    const uci::type::TaskPlanInputsType::ProposedTask& boundedList = accessor.getProposedTask();
    for (uci::type::TaskPlanInputsType::ProposedTask::size_type i = 0, end = boundedList.size(); i < end; ++i) {
      TaskAllocationType::serialize(boundedList.at(i), node, TaskPlanInputsType_Names::ProposedTask_Name);
    }
  }
  {
    const uci::type::TaskPlanInputsType::AssociationConstraint& boundedList = accessor.getAssociationConstraint();
    for (uci::type::TaskPlanInputsType::AssociationConstraint::size_type i = 0, end = boundedList.size(); i < end; ++i) {
      RequirementAssociationConstraintType::serialize(boundedList.at(i), node, TaskPlanInputsType_Names::AssociationConstraint_Name);
    }
  }
  if (accessor.hasOutputPlanParts()) {
    TaskPlanPartsType::serialize(accessor.getOutputPlanParts(), node, TaskPlanInputsType_Names::OutputPlanParts_Name);
  }
  if (createNode) {
    propTree.add_child(generatedNodeName, node);
  }
  return generatedNodeName;
}

} // namespace type

} // namespace extxml_uci

