/** @file COMINT_TaskBaseType.h
 *
 * @warning This file is automatically generated, edit at your own risk
 *
 * This file was generated on 04/01/2024 at 02:25:12 PM
 *
 * <pre>
 * Unclassified               U N C L A S S I F I E D               Unclassified
 *
 * DISTRIBUTION STATEMENT D: Distribution authorized to Department of Defense
 *    and U.S. DoD contractors only, Critical Technology, Export Controlled,
 *    26 January 2023. Other requests for this document shall be referred to
 *    AFLCMC/XA (OAMO), Wright-Patterson AFB OH 45433.
 *
 * DESTRUCTION NOTICE: Destroy by any method that will prevent disclosure of
 *    contents or reconstruction of the document.
 *
 * WARNING - This document contains technical data whose export is restricted
 *    by the Arms Export Control Act (Section 2751 of Title 22, United States
 *    Code) or the Export Control Reform Act of 2018 (Chapter 58 Sections
 *    4801-4852 of Title 50, United States Code). Violations of these export
 *    laws are subject to severe criminal penalties. Disseminate in accordance
 *    with provisions of DoD Directive 5230.25 and DoD Instruction 2040.02.
 *
 * Controlled by: USAF
 * Controlled by: AFLCMC/XA (OAMO)
 * CUI Category(ies): CTI, EXPT
 * Distribution Statement D
 * POC: Wayne Artuso, 937-713-5124
 *
 * CUI//SP-CTI/SP-EXPT
 * </pre>
 *
 */

#ifndef ASB_UCI_TYPE_COMINT_TASKBASETYPE_H
#define ASB_UCI_TYPE_COMINT_TASKBASETYPE_H

#include <memory>

#include <boost/optional/optional.hpp>
#include <boost/property_tree/ptree.hpp>

#include "asb_uci/base/BoundedList.h"
#include "asb_uci/type/COMINT_SubCapabilityEnum.h"
#include "uci/type/COMINT_TaskBaseType.h"

/**  */
namespace asb_uci {

/** The namespace in which all generated data types are declared */
namespace type {

class ProductOutputCommandBasicType;

/** See annotations in child elements and messages/elements that use this type for details. */
class COMINT_TaskBaseType : public virtual uci::type::COMINT_TaskBaseType {
public:
  /** Indicates a required output Product of the Task. See ProductTypeEnum for further details. [Occurrences: Minimum: 0;
    * Maximum: MAX_LENGTH]
    */
  using Output = asb_uci::base::BoundedList<uci::type::ProductOutputCommandBasicType, uci::type::accessorType::productOutputCommandBasicType, asb_uci::type::ProductOutputCommandBasicType>;

  /** The constructor */
  COMINT_TaskBaseType();

  /** The copy constructor
    *
    * @param rhs The COMINT_TaskBaseType to copy from
    */
  COMINT_TaskBaseType(const COMINT_TaskBaseType& rhs) = delete;

  /** The move constructor
    *
    * @param rhs The COMINT_TaskBaseType to move from
    */
  COMINT_TaskBaseType(COMINT_TaskBaseType&& rhs) = delete;

  /** The assignment operator
    *
    * @param rhs The COMINT_TaskBaseType to copy from
    * @return The COMINT_TaskBaseType that was assigned
    */
  COMINT_TaskBaseType& operator=(const COMINT_TaskBaseType& rhs) = delete;

  /** The move assignment operator
    *
    * @param rhs The COMINT_TaskBaseType to move from
    * @return The COMINT_TaskBaseType that was assigned
    */
  COMINT_TaskBaseType& operator=(COMINT_TaskBaseType&& rhs) = delete;

  /** The destructor */
  virtual ~COMINT_TaskBaseType();

  /** Performs a deep copy of the message data from the specified accessor into the object being operated on by copy(). Any
    * message data originally held by this object will be freed prior to the copy
    *
    * @param accessor The uci::type::COMINT_TaskBaseType whose contents are to be used to set this
    *      uci::type::COMINT_TaskBaseType's contents.
    */
  void copy(const uci::type::COMINT_TaskBaseType& accessor) override;

  /** Performs a deep copy of the message data from the specified accessor into the object being operated on by copy(). Any
    * message data originally held by this object will be freed prior to the copy
    *
    * @param accessor The uci::type::COMINT_TaskBaseType whose contents are to be used to set this
    *      uci::type::COMINT_TaskBaseType's contents.
    * @param checkIfDerivation Check if accessor to copy is a derived type.
    */
  void copyImpl(const uci::type::COMINT_TaskBaseType& accessor, bool checkIfDerivation);

  /** Resets the contents of this object returning these contents to their original state. */
  void reset() noexcept override;

  /** Returns the contents of the message's SubCapabilityType field
    *
    * @return The contents of the SubCapabilityType field
    */
  const uci::type::COMINT_SubCapabilityEnum& getSubCapabilityType() const override;

  /** Returns the contents of the message's SubCapabilityType field
    *
    * @return The contents of the SubCapabilityType field
    */
  uci::type::COMINT_SubCapabilityEnum& getSubCapabilityType() override;

  /** Sets the contents of the message's SubCapabilityType field
    *
    * @param accessor The accessor to use to set the SubCapabilityType field to
    * @return A reference to the object on which this method was called.
    */
  uci::type::COMINT_TaskBaseType& setSubCapabilityType(const uci::type::COMINT_SubCapabilityEnum& accessor) override;

  /** Sets the contents of the message's SubCapabilityType field
    *
    * @param value The new value to set the SubCapabilityType field to
    * @return A reference to the object on which this method was called.
    */
  uci::type::COMINT_TaskBaseType& setSubCapabilityType(uci::type::COMINT_SubCapabilityEnum::EnumerationItem value) override;

  /** Returns the accessor to the Output field contained in this message fragment
    *
    * @return The const reference to the accessor to the Output field.
    */
  const uci::type::COMINT_TaskBaseType::Output& getOutput() const override;

  /** Returns the accessor to the Output field contained in this message fragment
    *
    * @return The reference to the accessor to the Output field.
    */
  uci::type::COMINT_TaskBaseType::Output& getOutput() override;

  /** Set the contents of the message fragment that this accesssor provides access to to the contents the specified
    * accessor provides access to. A deep copy will be used by this method in setting the contents
    *
    * @param accessor The accessor to use to set the contents of the message fragment that this accessor provides access
    *      to.
    * @return A reference to the object on which this method was called.
    */
  uci::type::COMINT_TaskBaseType& setOutput(const uci::type::COMINT_TaskBaseType::Output& accessor) override;

  /** 
    *
    * @param type .
    * @return .
    */
  static std::unique_ptr<COMINT_TaskBaseType> create(uci::base::accessorType::AccessorType type);

  /** 
    *
    * @param propTree .
    * @param accessor .
    * @param nodeName .
    * @param nsPrefix .
    * @param topLevel .
    */
  static void deserialize(const boost::property_tree::ptree& propTree, uci::type::COMINT_TaskBaseType& accessor, std::string& nodeName, std::string& nsPrefix, bool topLevel = false);

  /** 
    *
    * @param accessor .
    * @param propTree .
    * @param nodeName .
    * @param createNode .
    * @param addTypeAttribute .
    * @param checkIfDerivation .
    * @param topLevel .
    * @return .
    */
  static std::string serialize(const uci::type::COMINT_TaskBaseType& accessor, boost::property_tree::ptree& propTree, const std::string& nodeName, bool createNode = true, bool addTypeAttribute = false, bool checkIfDerivation = true, bool topLevel = false);

private:
  std::unique_ptr<COMINT_SubCapabilityEnum> subCapabilityType_Accessor;
  std::unique_ptr<Output> output_Accessor;

};

} // namespace type

} // namespace asb_uci

#endif // ASB_UCI_TYPE_COMINT_TASKBASETYPE_H
