/** @file CommStarlinkControlStatusType.h
 *
 * @warning This file is automatically generated, edit at your own risk
 *
 * This file was generated on 04/01/2024 at 02:25:12 PM
 *
 * <pre>
 * Unclassified               U N C L A S S I F I E D               Unclassified
 *
 * DISTRIBUTION STATEMENT D: Distribution authorized to Department of Defense
 *    and U.S. DoD contractors only, Critical Technology, Export Controlled,
 *    26 January 2023. Other requests for this document shall be referred to
 *    AFLCMC/XA (OAMO), Wright-Patterson AFB OH 45433.
 *
 * DESTRUCTION NOTICE: Destroy by any method that will prevent disclosure of
 *    contents or reconstruction of the document.
 *
 * WARNING - This document contains technical data whose export is restricted
 *    by the Arms Export Control Act (Section 2751 of Title 22, United States
 *    Code) or the Export Control Reform Act of 2018 (Chapter 58 Sections
 *    4801-4852 of Title 50, United States Code). Violations of these export
 *    laws are subject to severe criminal penalties. Disseminate in accordance
 *    with provisions of DoD Directive 5230.25 and DoD Instruction 2040.02.
 *
 * Controlled by: USAF
 * Controlled by: AFLCMC/XA (OAMO)
 * CUI Category(ies): CTI, EXPT
 * Distribution Statement D
 * POC: Wayne Artuso, 937-713-5124
 *
 * CUI//SP-CTI/SP-EXPT
 * </pre>
 *
 */

#ifndef ASB_UCI_TYPE_COMMSTARLINKCONTROLSTATUSTYPE_H
#define ASB_UCI_TYPE_COMMSTARLINKCONTROLSTATUSTYPE_H

#include <memory>

#include <boost/optional/optional.hpp>
#include <boost/property_tree/ptree.hpp>

#include "../../../include/asb_uci/type/PointingControlModeStatusEnum.h"
#include "../../../include/asb_uci/type/PositionModeEnum.h"
#include "../../../../cppInterface/2.3.2/include/uci/type/CommStarlinkControlStatusType.h"

/**  */
namespace asb_uci {

/** The namespace in which all generated data types are declared */
namespace type {

class BeamPointingReferenceType;
class PolarizationType;
class TransceiverType;

/** See annotations in child elements and messages/elements that use this type for details. */
class CommStarlinkControlStatusType : public virtual uci::type::CommStarlinkControlStatusType {
public:
  /** The constructor */
  CommStarlinkControlStatusType();

  /** The copy constructor
    *
    * @param rhs The CommStarlinkControlStatusType to copy from
    */
  CommStarlinkControlStatusType(const CommStarlinkControlStatusType& rhs) = delete;

  /** The move constructor
    *
    * @param rhs The CommStarlinkControlStatusType to move from
    */
  CommStarlinkControlStatusType(CommStarlinkControlStatusType&& rhs) = delete;

  /** The assignment operator
    *
    * @param rhs The CommStarlinkControlStatusType to copy from
    * @return The CommStarlinkControlStatusType that was assigned
    */
  CommStarlinkControlStatusType& operator=(const CommStarlinkControlStatusType& rhs) = delete;

  /** The move assignment operator
    *
    * @param rhs The CommStarlinkControlStatusType to move from
    * @return The CommStarlinkControlStatusType that was assigned
    */
  CommStarlinkControlStatusType& operator=(CommStarlinkControlStatusType&& rhs) = delete;

  /** The destructor */
  virtual ~CommStarlinkControlStatusType();

  /** Performs a deep copy of the message data from the specified accessor into the object being operated on by copy(). Any
    * message data originally held by this object will be freed prior to the copy
    *
    * @param accessor The uci::type::CommStarlinkControlStatusType whose contents are to be used to set this
    *      uci::type::CommStarlinkControlStatusType's contents.
    */
  void copy(const uci::type::CommStarlinkControlStatusType& accessor) override;

  /** Performs a deep copy of the message data from the specified accessor into the object being operated on by copy(). Any
    * message data originally held by this object will be freed prior to the copy
    *
    * @param accessor The uci::type::CommStarlinkControlStatusType whose contents are to be used to set this
    *      uci::type::CommStarlinkControlStatusType's contents.
    * @param checkIfDerivation Check if accessor to copy is a derived type.
    */
  void copyImpl(const uci::type::CommStarlinkControlStatusType& accessor, bool checkIfDerivation);

  /** Resets the contents of this object returning these contents to their original state. */
  void reset() noexcept override;

  /** Returns the value of the optional field. Throws an exception is field is not set.
    *
    * @return The accessor that provides access to the contents of the optional field accessed by this accesor
    */
  uci::type::PositionModeEnum& getPositionMode_() const;

  /** Returns the value of the optional field. Throws an exception is field is not set.
    *
    * @return The accessor that provides access to the contents of the optional field accessed by this accesor
    */
  const uci::type::PositionModeEnum& getPositionMode() const override;

  /** Returns the value of the optional field. Throws an exception is field is not set.
    *
    * @return The accessor that provides access to the contents of the optional field accessed by this accesor
    */
  uci::type::PositionModeEnum& getPositionMode() override;

  /** Set the contents of the message fragment that this accesssor provides access to to the contents the specified
    * accessor provides access to. A deep copy will be used by this method in setting the contents
    *
    * @param accessor The accessor to use to set the contents of the message fragment that this accessor provides access
    *      to.
    * @return A reference to the object on which this method was called.
    */
  uci::type::CommStarlinkControlStatusType& setPositionMode(const uci::type::PositionModeEnum& accessor) override;

  /** Set the contents of the message fragment that this accesssor provides access to to the contents the specified
    * accessor provides access to. A deep copy will be used by this method in setting the contents
    *
    * @param value The accessor to use to set the contents of the message fragment that this accessor provides access to.
    * @return A reference to the object on which this method was called.
    */
  uci::type::CommStarlinkControlStatusType& setPositionMode(uci::type::PositionModeEnum::EnumerationItem value) override;

  /** Returns whether this optional field PositionModeis available
    *
    * @return Whether the optional field is available (true) or not (false).
    */
  bool hasPositionMode() const noexcept override;

  /** Enables the optional field such that getPositionMode will return the optional field and not throw an exception when
    * invoked.
    *
    * @param type The value to set the optional field to
    * @return The accessor that provides access to the contents of the optional field accessed by this accesor
    */
  uci::type::PositionModeEnum& enablePositionMode(uci::base::accessorType::AccessorType type = uci::base::accessorType::null) override;

  /** Clears the optional item marking it as not being set.
    *
    * @return A reference to the object on which this method was called.
    */
  uci::type::CommStarlinkControlStatusType& clearPositionMode() noexcept override;

  /** Returns the accessor that provides access to the contents of the optional field accessed by this accesor
    *
    * @return The accessor that provides access to the contents of the optional field accessed by this accesor
    */
  uci::type::TransceiverType& getTransceiver_() const;

  /** Returns the accessor that provides access to the contents of the optional field accessed by this accesor
    *
    * @return The accessor that provides access to the contents of the optional field accessed by this accesor
    */
  const uci::type::TransceiverType& getTransceiver() const override;

  /** Returns the accessor that provides access to the contents of the optional field accessed by this accesor
    *
    * @return The accessor that provides access to the contents of the optional field accessed by this accesor
    */
  uci::type::TransceiverType& getTransceiver() override;

  /** Set the contents of the message fragment that this accesssor provides access to to the contents the specified
    * accessor provides access to. A deep copy will be used by this method in setting the contents
    *
    * @param accessor The accessor to use to set the contents of the message fragment that this accessor provides access
    *      to.
    * @return A reference to the object on which this method was called.
    */
  uci::type::CommStarlinkControlStatusType& setTransceiver(const uci::type::TransceiverType& accessor) override;

  /** Returns whether this optional field Transceiveris available
    *
    * @return Whether the optional field is available (true) or not (false).
    */
  bool hasTransceiver() const noexcept override;

  /** Enables the optional field such that getTransceiver will return the optional field and not throw an exception when
    * invoked.
    *
    * @param type The value to set the optional field to
    * @return The accessor that provides access to the contents of the optional field accessed by this accesor
    */
  uci::type::TransceiverType& enableTransceiver(uci::base::accessorType::AccessorType type = uci::base::accessorType::null) override;

  /** Clears the value of the optional field accessed by this accesor
    *
    * @return A reference to the object on which this method was called.
    */
  uci::type::CommStarlinkControlStatusType& clearTransceiver() noexcept override;

  /** Returns the value of the optional field. Throws an exception is field is not set.
    *
    * @return The accessor that provides access to the contents of the optional field accessed by this accesor
    */
  uci::type::PointingControlModeStatusEnum& getPointingControlModeStatus_() const;

  /** Returns the value of the optional field. Throws an exception is field is not set.
    *
    * @return The accessor that provides access to the contents of the optional field accessed by this accesor
    */
  const uci::type::PointingControlModeStatusEnum& getPointingControlModeStatus() const override;

  /** Returns the value of the optional field. Throws an exception is field is not set.
    *
    * @return The accessor that provides access to the contents of the optional field accessed by this accesor
    */
  uci::type::PointingControlModeStatusEnum& getPointingControlModeStatus() override;

  /** Set the contents of the message fragment that this accesssor provides access to to the contents the specified
    * accessor provides access to. A deep copy will be used by this method in setting the contents
    *
    * @param accessor The accessor to use to set the contents of the message fragment that this accessor provides access
    *      to.
    * @return A reference to the object on which this method was called.
    */
  uci::type::CommStarlinkControlStatusType& setPointingControlModeStatus(const uci::type::PointingControlModeStatusEnum& accessor) override;

  /** Set the contents of the message fragment that this accesssor provides access to to the contents the specified
    * accessor provides access to. A deep copy will be used by this method in setting the contents
    *
    * @param value The accessor to use to set the contents of the message fragment that this accessor provides access to.
    * @return A reference to the object on which this method was called.
    */
  uci::type::CommStarlinkControlStatusType& setPointingControlModeStatus(uci::type::PointingControlModeStatusEnum::EnumerationItem value) override;

  /** Returns whether this optional field PointingControlModeStatusis available
    *
    * @return Whether the optional field is available (true) or not (false).
    */
  bool hasPointingControlModeStatus() const noexcept override;

  /** Enables the optional field such that getPointingControlModeStatus will return the optional field and not throw an
    * exception when invoked.
    *
    * @param type The value to set the optional field to
    * @return The accessor that provides access to the contents of the optional field accessed by this accesor
    */
  uci::type::PointingControlModeStatusEnum& enablePointingControlModeStatus(uci::base::accessorType::AccessorType type = uci::base::accessorType::null) override;

  /** Clears the optional item marking it as not being set.
    *
    * @return A reference to the object on which this method was called.
    */
  uci::type::CommStarlinkControlStatusType& clearPointingControlModeStatus() noexcept override;

  /** Returns the accessor that provides access to the contents of the optional field accessed by this accesor
    *
    * @return The accessor that provides access to the contents of the optional field accessed by this accesor
    */
  uci::type::BeamPointingReferenceType& getBeamPointing_() const;

  /** Returns the accessor that provides access to the contents of the optional field accessed by this accesor
    *
    * @return The accessor that provides access to the contents of the optional field accessed by this accesor
    */
  const uci::type::BeamPointingReferenceType& getBeamPointing() const override;

  /** Returns the accessor that provides access to the contents of the optional field accessed by this accesor
    *
    * @return The accessor that provides access to the contents of the optional field accessed by this accesor
    */
  uci::type::BeamPointingReferenceType& getBeamPointing() override;

  /** Set the contents of the message fragment that this accesssor provides access to to the contents the specified
    * accessor provides access to. A deep copy will be used by this method in setting the contents
    *
    * @param accessor The accessor to use to set the contents of the message fragment that this accessor provides access
    *      to.
    * @return A reference to the object on which this method was called.
    */
  uci::type::CommStarlinkControlStatusType& setBeamPointing(const uci::type::BeamPointingReferenceType& accessor) override;

  /** Returns whether this optional field BeamPointingis available
    *
    * @return Whether the optional field is available (true) or not (false).
    */
  bool hasBeamPointing() const noexcept override;

  /** Enables the optional field such that getBeamPointing will return the optional field and not throw an exception when
    * invoked.
    *
    * @param type The value to set the optional field to
    * @return The accessor that provides access to the contents of the optional field accessed by this accesor
    */
  uci::type::BeamPointingReferenceType& enableBeamPointing(uci::base::accessorType::AccessorType type = uci::base::accessorType::null) override;

  /** Clears the value of the optional field accessed by this accesor
    *
    * @return A reference to the object on which this method was called.
    */
  uci::type::CommStarlinkControlStatusType& clearBeamPointing() noexcept override;

  /** Returns the accessor that provides access to the contents of the optional field accessed by this accesor
    *
    * @return The accessor that provides access to the contents of the optional field accessed by this accesor
    */
  uci::type::PolarizationType& getPolarization_() const;

  /** Returns the accessor that provides access to the contents of the optional field accessed by this accesor
    *
    * @return The accessor that provides access to the contents of the optional field accessed by this accesor
    */
  const uci::type::PolarizationType& getPolarization() const override;

  /** Returns the accessor that provides access to the contents of the optional field accessed by this accesor
    *
    * @return The accessor that provides access to the contents of the optional field accessed by this accesor
    */
  uci::type::PolarizationType& getPolarization() override;

  /** Set the contents of the message fragment that this accesssor provides access to to the contents the specified
    * accessor provides access to. A deep copy will be used by this method in setting the contents
    *
    * @param accessor The accessor to use to set the contents of the message fragment that this accessor provides access
    *      to.
    * @return A reference to the object on which this method was called.
    */
  uci::type::CommStarlinkControlStatusType& setPolarization(const uci::type::PolarizationType& accessor) override;

  /** Returns whether this optional field Polarizationis available
    *
    * @return Whether the optional field is available (true) or not (false).
    */
  bool hasPolarization() const noexcept override;

  /** Enables the optional field such that getPolarization will return the optional field and not throw an exception when
    * invoked.
    *
    * @param type The value to set the optional field to
    * @return The accessor that provides access to the contents of the optional field accessed by this accesor
    */
  uci::type::PolarizationType& enablePolarization(uci::base::accessorType::AccessorType type = uci::base::accessorType::null) override;

  /** Clears the value of the optional field accessed by this accesor
    *
    * @return A reference to the object on which this method was called.
    */
  uci::type::CommStarlinkControlStatusType& clearPolarization() noexcept override;

  /** 
    *
    * @param type .
    * @return .
    */
  static std::unique_ptr<CommStarlinkControlStatusType> create(uci::base::accessorType::AccessorType type);

  /** 
    *
    * @param propTree .
    * @param accessor .
    * @param nodeName .
    * @param nsPrefix .
    * @param topLevel .
    */
  static void deserialize(const boost::property_tree::ptree& propTree, uci::type::CommStarlinkControlStatusType& accessor, std::string& nodeName, std::string& nsPrefix, bool topLevel = false);

  /** 
    *
    * @param accessor .
    * @param propTree .
    * @param nodeName .
    * @param createNode .
    * @param addTypeAttribute .
    * @param checkIfDerivation .
    * @param topLevel .
    * @return .
    */
  static std::string serialize(const uci::type::CommStarlinkControlStatusType& accessor, boost::property_tree::ptree& propTree, const std::string& nodeName, bool createNode = true, bool addTypeAttribute = false, bool checkIfDerivation = true, bool topLevel = false);

private:
  std::unique_ptr<PositionModeEnum> positionMode_Accessor;
  std::unique_ptr<TransceiverType> transceiver_Accessor;
  std::unique_ptr<PointingControlModeStatusEnum> pointingControlModeStatus_Accessor;
  std::unique_ptr<BeamPointingReferenceType> beamPointing_Accessor;
  std::unique_ptr<PolarizationType> polarization_Accessor;

};

} // namespace type

} // namespace asb_uci

#endif // ASB_UCI_TYPE_COMMSTARLINKCONTROLSTATUSTYPE_H
