/** @file ComponentStatusDataRequestMDT.h
 *
 * @warning This file is automatically generated, edit at your own risk
 *
 * This file was generated on 04/01/2024 at 02:25:12 PM
 *
 * <pre>
 * Unclassified               U N C L A S S I F I E D               Unclassified
 *
 * DISTRIBUTION STATEMENT D: Distribution authorized to Department of Defense
 *    and U.S. DoD contractors only, Critical Technology, Export Controlled,
 *    26 January 2023. Other requests for this document shall be referred to
 *    AFLCMC/XA (OAMO), Wright-Patterson AFB OH 45433.
 *
 * DESTRUCTION NOTICE: Destroy by any method that will prevent disclosure of
 *    contents or reconstruction of the document.
 *
 * WARNING - This document contains technical data whose export is restricted
 *    by the Arms Export Control Act (Section 2751 of Title 22, United States
 *    Code) or the Export Control Reform Act of 2018 (Chapter 58 Sections
 *    4801-4852 of Title 50, United States Code). Violations of these export
 *    laws are subject to severe criminal penalties. Disseminate in accordance
 *    with provisions of DoD Directive 5230.25 and DoD Instruction 2040.02.
 *
 * Controlled by: USAF
 * Controlled by: AFLCMC/XA (OAMO)
 * CUI Category(ies): CTI, EXPT
 * Distribution Statement D
 * POC: Wayne Artuso, 937-713-5124
 *
 * CUI//SP-CTI/SP-EXPT
 * </pre>
 *
 */

#ifndef ASB_UCI_TYPE_COMPONENTSTATUSDATAREQUESTMDT_H
#define ASB_UCI_TYPE_COMPONENTSTATUSDATAREQUESTMDT_H

#include <memory>

#include <boost/optional/optional.hpp>
#include <boost/property_tree/ptree.hpp>

#include "../../../include/asb_uci/base/BoundedList.h"
#include "../../../include/asb_uci/type/ComponentStatusRequestEnum.h"
#include "../../../include/asb_uci/type/RequestBaseType.h"
#include "../../../../cppInterface/2.3.2/include/uci/type/ComponentStatusDataRequestMDT.h"

/**  */
namespace asb_uci {

/** The namespace in which all generated data types are declared */
namespace type {

class ComponentID_Type;
class ServiceID_Type;

/** The message data for the ComponentStatusRequest Message. */
class ComponentStatusDataRequestMDT : public virtual uci::type::ComponentStatusDataRequestMDT, public virtual RequestBaseType {
public:
  /** The Service or Services to report ComponentStatus. If empty then all Services ComponentStatus are requested. A
    * Service may report the status for several components and/or several kinds of components. [Occurrences: Minimum: 0;
    * Maximum: MAX_LENGTH]
    */
  using ServiceID = asb_uci::base::BoundedList<uci::type::ServiceID_Type, uci::type::accessorType::serviceID_Type, asb_uci::type::ServiceID_Type>;

  /** Indicates the unique ID of the component or components corresponding to this Request. If empty all component statuses
    * are requested. [Occurrences: Minimum: 0; Maximum: MAX_LENGTH]
    */
  using ComponentID = asb_uci::base::BoundedList<uci::type::ComponentID_Type, uci::type::accessorType::componentID_Type, asb_uci::type::ComponentID_Type>;

  /** The constructor */
  ComponentStatusDataRequestMDT();

  /** The copy constructor
    *
    * @param rhs The ComponentStatusDataRequestMDT to copy from
    */
  ComponentStatusDataRequestMDT(const ComponentStatusDataRequestMDT& rhs) = delete;

  /** The move constructor
    *
    * @param rhs The ComponentStatusDataRequestMDT to move from
    */
  ComponentStatusDataRequestMDT(ComponentStatusDataRequestMDT&& rhs) = delete;

  /** The assignment operator
    *
    * @param rhs The ComponentStatusDataRequestMDT to copy from
    * @return The ComponentStatusDataRequestMDT that was assigned
    */
  ComponentStatusDataRequestMDT& operator=(const ComponentStatusDataRequestMDT& rhs) = delete;

  /** The move assignment operator
    *
    * @param rhs The ComponentStatusDataRequestMDT to move from
    * @return The ComponentStatusDataRequestMDT that was assigned
    */
  ComponentStatusDataRequestMDT& operator=(ComponentStatusDataRequestMDT&& rhs) = delete;

  /** The destructor */
  ~ComponentStatusDataRequestMDT() override;

  /** Performs a deep copy of the message data from the specified accessor into the object being operated on by copy(). Any
    * message data originally held by this object will be freed prior to the copy
    *
    * @param accessor The uci::type::ComponentStatusDataRequestMDT whose contents are to be used to set this
    *      uci::type::ComponentStatusDataRequestMDT's contents.
    */
  void copy(const uci::type::ComponentStatusDataRequestMDT& accessor) override;

  /** Performs a deep copy of the message data from the specified accessor into the object being operated on by copy(). Any
    * message data originally held by this object will be freed prior to the copy
    *
    * @param accessor The uci::type::ComponentStatusDataRequestMDT whose contents are to be used to set this
    *      uci::type::ComponentStatusDataRequestMDT's contents.
    * @param checkIfDerivation Check if accessor to copy is a derived type.
    */
  void copyImpl(const uci::type::ComponentStatusDataRequestMDT& accessor, bool checkIfDerivation);

  /** Resets the contents of this object returning these contents to their original state. */
  void reset() noexcept override;

  /** Returns the contents of the message's StatusType field
    *
    * @return The contents of the StatusType field
    */
  const uci::type::ComponentStatusRequestEnum& getStatusType() const override;

  /** Returns the contents of the message's StatusType field
    *
    * @return The contents of the StatusType field
    */
  uci::type::ComponentStatusRequestEnum& getStatusType() override;

  /** Sets the contents of the message's StatusType field
    *
    * @param accessor The accessor to use to set the StatusType field to
    * @return A reference to the object on which this method was called.
    */
  uci::type::ComponentStatusDataRequestMDT& setStatusType(const uci::type::ComponentStatusRequestEnum& accessor) override;

  /** Sets the contents of the message's StatusType field
    *
    * @param value The new value to set the StatusType field to
    * @return A reference to the object on which this method was called.
    */
  uci::type::ComponentStatusDataRequestMDT& setStatusType(uci::type::ComponentStatusRequestEnum::EnumerationItem value) override;

  /** Returns the accessor to the ServiceID field contained in this message fragment
    *
    * @return The const reference to the accessor to the ServiceID field.
    */
  const uci::type::ComponentStatusDataRequestMDT::ServiceID& getServiceID() const override;

  /** Returns the accessor to the ServiceID field contained in this message fragment
    *
    * @return The reference to the accessor to the ServiceID field.
    */
  uci::type::ComponentStatusDataRequestMDT::ServiceID& getServiceID() override;

  /** Set the contents of the message fragment that this accesssor provides access to to the contents the specified
    * accessor provides access to. A deep copy will be used by this method in setting the contents
    *
    * @param accessor The accessor to use to set the contents of the message fragment that this accessor provides access
    *      to.
    * @return A reference to the object on which this method was called.
    */
  uci::type::ComponentStatusDataRequestMDT& setServiceID(const uci::type::ComponentStatusDataRequestMDT::ServiceID& accessor) override;

  /** Returns the accessor to the ComponentID field contained in this message fragment
    *
    * @return The const reference to the accessor to the ComponentID field.
    */
  const uci::type::ComponentStatusDataRequestMDT::ComponentID& getComponentID() const override;

  /** Returns the accessor to the ComponentID field contained in this message fragment
    *
    * @return The reference to the accessor to the ComponentID field.
    */
  uci::type::ComponentStatusDataRequestMDT::ComponentID& getComponentID() override;

  /** Set the contents of the message fragment that this accesssor provides access to to the contents the specified
    * accessor provides access to. A deep copy will be used by this method in setting the contents
    *
    * @param accessor The accessor to use to set the contents of the message fragment that this accessor provides access
    *      to.
    * @return A reference to the object on which this method was called.
    */
  uci::type::ComponentStatusDataRequestMDT& setComponentID(const uci::type::ComponentStatusDataRequestMDT::ComponentID& accessor) override;

  /** 
    *
    * @param type .
    * @return .
    */
  static std::unique_ptr<ComponentStatusDataRequestMDT> create(uci::base::accessorType::AccessorType type);

  /** 
    *
    * @param propTree .
    * @param accessor .
    * @param nodeName .
    * @param nsPrefix .
    * @param topLevel .
    */
  static void deserialize(const boost::property_tree::ptree& propTree, uci::type::ComponentStatusDataRequestMDT& accessor, std::string& nodeName, std::string& nsPrefix, bool topLevel = false);

  /** 
    *
    * @param accessor .
    * @param propTree .
    * @param nodeName .
    * @param createNode .
    * @param addTypeAttribute .
    * @param checkIfDerivation .
    * @param topLevel .
    * @return .
    */
  static std::string serialize(const uci::type::ComponentStatusDataRequestMDT& accessor, boost::property_tree::ptree& propTree, const std::string& nodeName, bool createNode = true, bool addTypeAttribute = false, bool checkIfDerivation = true, bool topLevel = false);

private:
  std::unique_ptr<ComponentStatusRequestEnum> statusType_Accessor;
  std::unique_ptr<ServiceID> serviceID_Accessor;
  std::unique_ptr<ComponentID> componentID_Accessor;

};

} // namespace type

} // namespace asb_uci

#endif // ASB_UCI_TYPE_COMPONENTSTATUSDATAREQUESTMDT_H
