/** @file IFF_ConsentRequestType.h
 *
 * @warning This file is automatically generated, edit at your own risk
 *
 * This file was generated on 04/01/2024 at 02:25:13 PM
 *
 * <pre>
 * Unclassified               U N C L A S S I F I E D               Unclassified
 *
 * DISTRIBUTION STATEMENT D: Distribution authorized to Department of Defense
 *    and U.S. DoD contractors only, Critical Technology, Export Controlled,
 *    26 January 2023. Other requests for this document shall be referred to
 *    AFLCMC/XA (OAMO), Wright-Patterson AFB OH 45433.
 *
 * DESTRUCTION NOTICE: Destroy by any method that will prevent disclosure of
 *    contents or reconstruction of the document.
 *
 * WARNING - This document contains technical data whose export is restricted
 *    by the Arms Export Control Act (Section 2751 of Title 22, United States
 *    Code) or the Export Control Reform Act of 2018 (Chapter 58 Sections
 *    4801-4852 of Title 50, United States Code). Violations of these export
 *    laws are subject to severe criminal penalties. Disseminate in accordance
 *    with provisions of DoD Directive 5230.25 and DoD Instruction 2040.02.
 *
 * Controlled by: USAF
 * Controlled by: AFLCMC/XA (OAMO)
 * CUI Category(ies): CTI, EXPT
 * Distribution Statement D
 * POC: Wayne Artuso, 937-713-5124
 *
 * CUI//SP-CTI/SP-EXPT
 * </pre>
 *
 */

#ifndef ASB_UCI_TYPE_IFF_CONSENTREQUESTTYPE_H
#define ASB_UCI_TYPE_IFF_CONSENTREQUESTTYPE_H

#include <memory>

#include <boost/optional/optional.hpp>
#include <boost/property_tree/ptree.hpp>

#include "asb_uci/type/RequestBaseType.h"
#include "asb_xs/type/simpleXmlSchemaPrimitives.h"
#include "uci/type/IFF_ConsentRequestType.h"

/**  */
namespace asb_uci {

/** The namespace in which all generated data types are declared */
namespace type {

class ActivityID_Type;

/** See annotations in child elements and messages/elements that use this type for details. */
class IFF_ConsentRequestType : public virtual uci::type::IFF_ConsentRequestType, public virtual RequestBaseType {
public:
  /** The constructor */
  IFF_ConsentRequestType();

  /** The copy constructor
    *
    * @param rhs The IFF_ConsentRequestType to copy from
    */
  IFF_ConsentRequestType(const IFF_ConsentRequestType& rhs) = delete;

  /** The move constructor
    *
    * @param rhs The IFF_ConsentRequestType to move from
    */
  IFF_ConsentRequestType(IFF_ConsentRequestType&& rhs) = delete;

  /** The assignment operator
    *
    * @param rhs The IFF_ConsentRequestType to copy from
    * @return The IFF_ConsentRequestType that was assigned
    */
  IFF_ConsentRequestType& operator=(const IFF_ConsentRequestType& rhs) = delete;

  /** The move assignment operator
    *
    * @param rhs The IFF_ConsentRequestType to move from
    * @return The IFF_ConsentRequestType that was assigned
    */
  IFF_ConsentRequestType& operator=(IFF_ConsentRequestType&& rhs) = delete;

  /** The destructor */
  ~IFF_ConsentRequestType() override;

  /** Performs a deep copy of the message data from the specified accessor into the object being operated on by copy(). Any
    * message data originally held by this object will be freed prior to the copy
    *
    * @param accessor The uci::type::IFF_ConsentRequestType whose contents are to be used to set this
    *      uci::type::IFF_ConsentRequestType's contents.
    */
  void copy(const uci::type::IFF_ConsentRequestType& accessor) override;

  /** Performs a deep copy of the message data from the specified accessor into the object being operated on by copy(). Any
    * message data originally held by this object will be freed prior to the copy
    *
    * @param accessor The uci::type::IFF_ConsentRequestType whose contents are to be used to set this
    *      uci::type::IFF_ConsentRequestType's contents.
    * @param checkIfDerivation Check if accessor to copy is a derived type.
    */
  void copyImpl(const uci::type::IFF_ConsentRequestType& accessor, bool checkIfDerivation);

  /** Resets the contents of this object returning these contents to their original state. */
  void reset() noexcept override;

  /** Returns the accessor to the ActivityID field contained in this message fragment
    *
    * @return The const reference to the accessor to the ActivityID field.
    */
  const uci::type::ActivityID_Type& getActivityID() const override;

  /** Returns the accessor to the ActivityID field contained in this message fragment
    *
    * @return The reference to the accessor to the ActivityID field.
    */
  uci::type::ActivityID_Type& getActivityID() override;

  /** Set the contents of the message fragment that this accesssor provides access to to the contents the specified
    * accessor provides access to. A deep copy will be used by this method in setting the contents
    *
    * @param accessor The accessor to use to set the contents of the message fragment that this accessor provides access
    *      to.
    * @return A reference to the object on which this method was called.
    */
  uci::type::IFF_ConsentRequestType& setActivityID(const uci::type::ActivityID_Type& accessor) override;

  /** Returns the contents of the message's RF_Override field
    *
    * @return The contents of the RF_Override field
    */
  xs::Boolean getRF_Override() const override;

  /** Sets the contents of the message's RF_Override field
    *
    * @param value The new value to set the RF_Override field to
    * @return A reference to the object on which this method was called.
    */
  uci::type::IFF_ConsentRequestType& setRF_Override(xs::Boolean value) override;

  /** 
    *
    * @param type .
    * @return .
    */
  static std::unique_ptr<IFF_ConsentRequestType> create(uci::base::accessorType::AccessorType type);

  /** 
    *
    * @param propTree .
    * @param accessor .
    * @param nodeName .
    * @param nsPrefix .
    * @param topLevel .
    */
  static void deserialize(const boost::property_tree::ptree& propTree, uci::type::IFF_ConsentRequestType& accessor, std::string& nodeName, std::string& nsPrefix, bool topLevel = false);

  /** 
    *
    * @param accessor .
    * @param propTree .
    * @param nodeName .
    * @param createNode .
    * @param addTypeAttribute .
    * @param checkIfDerivation .
    * @param topLevel .
    * @return .
    */
  static std::string serialize(const uci::type::IFF_ConsentRequestType& accessor, boost::property_tree::ptree& propTree, const std::string& nodeName, bool createNode = true, bool addTypeAttribute = false, bool checkIfDerivation = true, bool topLevel = false);

private:
  std::unique_ptr<ActivityID_Type> activityID_Accessor;
  asb_xs::Boolean rF_Override_Accessor{false};

};

} // namespace type

} // namespace asb_uci

#endif // ASB_UCI_TYPE_IFF_CONSENTREQUESTTYPE_H
