/** @file PackagePartnerStatusType.h
 *
 * @warning This file is automatically generated, edit at your own risk
 *
 * This file was generated on 04/01/2024 at 02:25:14 PM
 *
 * <pre>
 * Unclassified               U N C L A S S I F I E D               Unclassified
 *
 * DISTRIBUTION STATEMENT D: Distribution authorized to Department of Defense
 *    and U.S. DoD contractors only, Critical Technology, Export Controlled,
 *    26 January 2023. Other requests for this document shall be referred to
 *    AFLCMC/XA (OAMO), Wright-Patterson AFB OH 45433.
 *
 * DESTRUCTION NOTICE: Destroy by any method that will prevent disclosure of
 *    contents or reconstruction of the document.
 *
 * WARNING - This document contains technical data whose export is restricted
 *    by the Arms Export Control Act (Section 2751 of Title 22, United States
 *    Code) or the Export Control Reform Act of 2018 (Chapter 58 Sections
 *    4801-4852 of Title 50, United States Code). Violations of these export
 *    laws are subject to severe criminal penalties. Disseminate in accordance
 *    with provisions of DoD Directive 5230.25 and DoD Instruction 2040.02.
 *
 * Controlled by: USAF
 * Controlled by: AFLCMC/XA (OAMO)
 * CUI Category(ies): CTI, EXPT
 * Distribution Statement D
 * POC: Wayne Artuso, 937-713-5124
 *
 * CUI//SP-CTI/SP-EXPT
 * </pre>
 *
 */

#ifndef ASB_UCI_TYPE_PACKAGEPARTNERSTATUSTYPE_H
#define ASB_UCI_TYPE_PACKAGEPARTNERSTATUSTYPE_H

#include <memory>

#include <boost/optional/optional.hpp>
#include <boost/property_tree/ptree.hpp>

#include "asb_uci/base/BoundedList.h"
#include "asb_uci/type/SystemSourceEnum.h"
#include "asb_uci/type/SystemStateEnum.h"
#include "uci/type/PackagePartnerStatusType.h"

/**  */
namespace asb_uci {

/** The namespace in which all generated data types are declared */
namespace type {

class CapabilityStatusType;
class SystemID_Type;

/** See annotations in child elements and messages/elements that use this type for details. */
class PackagePartnerStatusType : public virtual uci::type::PackagePartnerStatusType {
public:
  /** Indicates package-related status and details for a partnered Capability in the package. [Occurrences: Minimum: 1;
    * Maximum: MAX_LENGTH]
    */
  using PartnerCapabilityStatus = asb_uci::base::BoundedList<uci::type::CapabilityStatusType, uci::type::accessorType::capabilityStatusType, asb_uci::type::CapabilityStatusType>;

  /** The constructor */
  PackagePartnerStatusType();

  /** The copy constructor
    *
    * @param rhs The PackagePartnerStatusType to copy from
    */
  PackagePartnerStatusType(const PackagePartnerStatusType& rhs) = delete;

  /** The move constructor
    *
    * @param rhs The PackagePartnerStatusType to move from
    */
  PackagePartnerStatusType(PackagePartnerStatusType&& rhs) = delete;

  /** The assignment operator
    *
    * @param rhs The PackagePartnerStatusType to copy from
    * @return The PackagePartnerStatusType that was assigned
    */
  PackagePartnerStatusType& operator=(const PackagePartnerStatusType& rhs) = delete;

  /** The move assignment operator
    *
    * @param rhs The PackagePartnerStatusType to move from
    * @return The PackagePartnerStatusType that was assigned
    */
  PackagePartnerStatusType& operator=(PackagePartnerStatusType&& rhs) = delete;

  /** The destructor */
  virtual ~PackagePartnerStatusType();

  /** Performs a deep copy of the message data from the specified accessor into the object being operated on by copy(). Any
    * message data originally held by this object will be freed prior to the copy
    *
    * @param accessor The uci::type::PackagePartnerStatusType whose contents are to be used to set this
    *      uci::type::PackagePartnerStatusType's contents.
    */
  void copy(const uci::type::PackagePartnerStatusType& accessor) override;

  /** Performs a deep copy of the message data from the specified accessor into the object being operated on by copy(). Any
    * message data originally held by this object will be freed prior to the copy
    *
    * @param accessor The uci::type::PackagePartnerStatusType whose contents are to be used to set this
    *      uci::type::PackagePartnerStatusType's contents.
    * @param checkIfDerivation Check if accessor to copy is a derived type.
    */
  void copyImpl(const uci::type::PackagePartnerStatusType& accessor, bool checkIfDerivation);

  /** Resets the contents of this object returning these contents to their original state. */
  void reset() noexcept override;

  /** Returns the accessor to the SystemID field contained in this message fragment
    *
    * @return The const reference to the accessor to the SystemID field.
    */
  const uci::type::SystemID_Type& getSystemID() const override;

  /** Returns the accessor to the SystemID field contained in this message fragment
    *
    * @return The reference to the accessor to the SystemID field.
    */
  uci::type::SystemID_Type& getSystemID() override;

  /** Set the contents of the message fragment that this accesssor provides access to to the contents the specified
    * accessor provides access to. A deep copy will be used by this method in setting the contents
    *
    * @param accessor The accessor to use to set the contents of the message fragment that this accessor provides access
    *      to.
    * @return A reference to the object on which this method was called.
    */
  uci::type::PackagePartnerStatusType& setSystemID(const uci::type::SystemID_Type& accessor) override;

  /** Returns the contents of the message's PartnerState field
    *
    * @return The contents of the PartnerState field
    */
  const uci::type::SystemStateEnum& getPartnerState() const override;

  /** Returns the contents of the message's PartnerState field
    *
    * @return The contents of the PartnerState field
    */
  uci::type::SystemStateEnum& getPartnerState() override;

  /** Sets the contents of the message's PartnerState field
    *
    * @param accessor The accessor to use to set the PartnerState field to
    * @return A reference to the object on which this method was called.
    */
  uci::type::PackagePartnerStatusType& setPartnerState(const uci::type::SystemStateEnum& accessor) override;

  /** Sets the contents of the message's PartnerState field
    *
    * @param value The new value to set the PartnerState field to
    * @return A reference to the object on which this method was called.
    */
  uci::type::PackagePartnerStatusType& setPartnerState(uci::type::SystemStateEnum::EnumerationItem value) override;

  /** Returns the contents of the message's PartnerSource field
    *
    * @return The contents of the PartnerSource field
    */
  const uci::type::SystemSourceEnum& getPartnerSource() const override;

  /** Returns the contents of the message's PartnerSource field
    *
    * @return The contents of the PartnerSource field
    */
  uci::type::SystemSourceEnum& getPartnerSource() override;

  /** Sets the contents of the message's PartnerSource field
    *
    * @param accessor The accessor to use to set the PartnerSource field to
    * @return A reference to the object on which this method was called.
    */
  uci::type::PackagePartnerStatusType& setPartnerSource(const uci::type::SystemSourceEnum& accessor) override;

  /** Sets the contents of the message's PartnerSource field
    *
    * @param value The new value to set the PartnerSource field to
    * @return A reference to the object on which this method was called.
    */
  uci::type::PackagePartnerStatusType& setPartnerSource(uci::type::SystemSourceEnum::EnumerationItem value) override;

  /** Returns the accessor to the PartnerCapabilityStatus field contained in this message fragment
    *
    * @return The const reference to the accessor to the PartnerCapabilityStatus field.
    */
  const uci::type::PackagePartnerStatusType::PartnerCapabilityStatus& getPartnerCapabilityStatus() const override;

  /** Returns the accessor to the PartnerCapabilityStatus field contained in this message fragment
    *
    * @return The reference to the accessor to the PartnerCapabilityStatus field.
    */
  uci::type::PackagePartnerStatusType::PartnerCapabilityStatus& getPartnerCapabilityStatus() override;

  /** Set the contents of the message fragment that this accesssor provides access to to the contents the specified
    * accessor provides access to. A deep copy will be used by this method in setting the contents
    *
    * @param accessor The accessor to use to set the contents of the message fragment that this accessor provides access
    *      to.
    * @return A reference to the object on which this method was called.
    */
  uci::type::PackagePartnerStatusType& setPartnerCapabilityStatus(const uci::type::PackagePartnerStatusType::PartnerCapabilityStatus& accessor) override;

  /** 
    *
    * @param type .
    * @return .
    */
  static std::unique_ptr<PackagePartnerStatusType> create(uci::base::accessorType::AccessorType type);

  /** 
    *
    * @param propTree .
    * @param accessor .
    * @param nodeName .
    * @param nsPrefix .
    * @param topLevel .
    */
  static void deserialize(const boost::property_tree::ptree& propTree, uci::type::PackagePartnerStatusType& accessor, std::string& nodeName, std::string& nsPrefix, bool topLevel = false);

  /** 
    *
    * @param accessor .
    * @param propTree .
    * @param nodeName .
    * @param createNode .
    * @param addTypeAttribute .
    * @param checkIfDerivation .
    * @param topLevel .
    * @return .
    */
  static std::string serialize(const uci::type::PackagePartnerStatusType& accessor, boost::property_tree::ptree& propTree, const std::string& nodeName, bool createNode = true, bool addTypeAttribute = false, bool checkIfDerivation = true, bool topLevel = false);

private:
  std::unique_ptr<SystemID_Type> systemID_Accessor;
  std::unique_ptr<SystemStateEnum> partnerState_Accessor;
  std::unique_ptr<SystemSourceEnum> partnerSource_Accessor;
  std::unique_ptr<PartnerCapabilityStatus> partnerCapabilityStatus_Accessor;

};

} // namespace type

} // namespace asb_uci

#endif // ASB_UCI_TYPE_PACKAGEPARTNERSTATUSTYPE_H
