/** @file SignalEmitterKinematicsFixedType.h
 *
 * @warning This file is automatically generated, edit at your own risk
 *
 * This file was generated on 04/01/2024 at 02:25:15 PM
 *
 * <pre>
 * Unclassified               U N C L A S S I F I E D               Unclassified
 *
 * DISTRIBUTION STATEMENT D: Distribution authorized to Department of Defense
 *    and U.S. DoD contractors only, Critical Technology, Export Controlled,
 *    26 January 2023. Other requests for this document shall be referred to
 *    AFLCMC/XA (OAMO), Wright-Patterson AFB OH 45433.
 *
 * DESTRUCTION NOTICE: Destroy by any method that will prevent disclosure of
 *    contents or reconstruction of the document.
 *
 * WARNING - This document contains technical data whose export is restricted
 *    by the Arms Export Control Act (Section 2751 of Title 22, United States
 *    Code) or the Export Control Reform Act of 2018 (Chapter 58 Sections
 *    4801-4852 of Title 50, United States Code). Violations of these export
 *    laws are subject to severe criminal penalties. Disseminate in accordance
 *    with provisions of DoD Directive 5230.25 and DoD Instruction 2040.02.
 *
 * Controlled by: USAF
 * Controlled by: AFLCMC/XA (OAMO)
 * CUI Category(ies): CTI, EXPT
 * Distribution Statement D
 * POC: Wayne Artuso, 937-713-5124
 *
 * CUI//SP-CTI/SP-EXPT
 * </pre>
 *
 */

#ifndef ASB_UCI_TYPE_SIGNALEMITTERKINEMATICSFIXEDTYPE_H
#define ASB_UCI_TYPE_SIGNALEMITTERKINEMATICSFIXEDTYPE_H

#include <memory>

#include <boost/optional/optional.hpp>
#include <boost/property_tree/ptree.hpp>

#include "../../../include/asb_uci/base/BoundedList.h"
#include "../../../include/asb_uci/type/EW_FixEnum.h"
#include "../../../include/asb_uci/type/EmitterFixedPositionType.h"
#include "../../../../cppInterface/2.3.2/include/uci/type/SignalEmitterKinematicsFixedType.h"

/**  */
namespace asb_uci {

/** The namespace in which all generated data types are declared */
namespace type {

class SignalEmitterKinematicsFixedGeolocationStatusType;

/** See annotations in child elements and messages/elements that use this type for details. */
class SignalEmitterKinematicsFixedType : public virtual uci::type::SignalEmitterKinematicsFixedType, public virtual EmitterFixedPositionType {
public:
  /** Indicates the status of a method of geolocation used to determine the emitter position. Multiple instances allows the
    * last state of multiple methods to be reported. If multiple instances are given, each should be of a different
    * geolocation method as indicated by the child element. [Occurrences: Minimum: 0; Maximum: 8]
    */
  using GeolocationStatus = asb_uci::base::BoundedList<uci::type::SignalEmitterKinematicsFixedGeolocationStatusType, uci::type::accessorType::signalEmitterKinematicsFixedGeolocationStatusType, asb_uci::type::SignalEmitterKinematicsFixedGeolocationStatusType>;

  /** The constructor */
  SignalEmitterKinematicsFixedType();

  /** The copy constructor
    *
    * @param rhs The SignalEmitterKinematicsFixedType to copy from
    */
  SignalEmitterKinematicsFixedType(const SignalEmitterKinematicsFixedType& rhs) = delete;

  /** The move constructor
    *
    * @param rhs The SignalEmitterKinematicsFixedType to move from
    */
  SignalEmitterKinematicsFixedType(SignalEmitterKinematicsFixedType&& rhs) = delete;

  /** The assignment operator
    *
    * @param rhs The SignalEmitterKinematicsFixedType to copy from
    * @return The SignalEmitterKinematicsFixedType that was assigned
    */
  SignalEmitterKinematicsFixedType& operator=(const SignalEmitterKinematicsFixedType& rhs) = delete;

  /** The move assignment operator
    *
    * @param rhs The SignalEmitterKinematicsFixedType to move from
    * @return The SignalEmitterKinematicsFixedType that was assigned
    */
  SignalEmitterKinematicsFixedType& operator=(SignalEmitterKinematicsFixedType&& rhs) = delete;

  /** The destructor */
  ~SignalEmitterKinematicsFixedType() override;

  /** Performs a deep copy of the message data from the specified accessor into the object being operated on by copy(). Any
    * message data originally held by this object will be freed prior to the copy
    *
    * @param accessor The uci::type::SignalEmitterKinematicsFixedType whose contents are to be used to set this
    *      uci::type::SignalEmitterKinematicsFixedType's contents.
    */
  void copy(const uci::type::SignalEmitterKinematicsFixedType& accessor) override;

  /** Performs a deep copy of the message data from the specified accessor into the object being operated on by copy(). Any
    * message data originally held by this object will be freed prior to the copy
    *
    * @param accessor The uci::type::SignalEmitterKinematicsFixedType whose contents are to be used to set this
    *      uci::type::SignalEmitterKinematicsFixedType's contents.
    * @param checkIfDerivation Check if accessor to copy is a derived type.
    */
  void copyImpl(const uci::type::SignalEmitterKinematicsFixedType& accessor, bool checkIfDerivation);

  /** Resets the contents of this object returning these contents to their original state. */
  void reset() noexcept override;

  /** Returns the accessor to the GeolocationStatus field contained in this message fragment
    *
    * @return The const reference to the accessor to the GeolocationStatus field.
    */
  const uci::type::SignalEmitterKinematicsFixedType::GeolocationStatus& getGeolocationStatus() const override;

  /** Returns the accessor to the GeolocationStatus field contained in this message fragment
    *
    * @return The reference to the accessor to the GeolocationStatus field.
    */
  uci::type::SignalEmitterKinematicsFixedType::GeolocationStatus& getGeolocationStatus() override;

  /** Set the contents of the message fragment that this accesssor provides access to to the contents the specified
    * accessor provides access to. A deep copy will be used by this method in setting the contents
    *
    * @param accessor The accessor to use to set the contents of the message fragment that this accessor provides access
    *      to.
    * @return A reference to the object on which this method was called.
    */
  uci::type::SignalEmitterKinematicsFixedType& setGeolocationStatus(const uci::type::SignalEmitterKinematicsFixedType::GeolocationStatus& accessor) override;

  /** Returns the value of the optional field. Throws an exception is field is not set.
    *
    * @return The accessor that provides access to the contents of the optional field accessed by this accesor
    */
  uci::type::EW_FixEnum& getEW_FixType_() const;

  /** Returns the value of the optional field. Throws an exception is field is not set.
    *
    * @return The accessor that provides access to the contents of the optional field accessed by this accesor
    */
  const uci::type::EW_FixEnum& getEW_FixType() const override;

  /** Returns the value of the optional field. Throws an exception is field is not set.
    *
    * @return The accessor that provides access to the contents of the optional field accessed by this accesor
    */
  uci::type::EW_FixEnum& getEW_FixType() override;

  /** Set the contents of the message fragment that this accesssor provides access to to the contents the specified
    * accessor provides access to. A deep copy will be used by this method in setting the contents
    *
    * @param accessor The accessor to use to set the contents of the message fragment that this accessor provides access
    *      to.
    * @return A reference to the object on which this method was called.
    */
  uci::type::SignalEmitterKinematicsFixedType& setEW_FixType(const uci::type::EW_FixEnum& accessor) override;

  /** Set the contents of the message fragment that this accesssor provides access to to the contents the specified
    * accessor provides access to. A deep copy will be used by this method in setting the contents
    *
    * @param value The accessor to use to set the contents of the message fragment that this accessor provides access to.
    * @return A reference to the object on which this method was called.
    */
  uci::type::SignalEmitterKinematicsFixedType& setEW_FixType(uci::type::EW_FixEnum::EnumerationItem value) override;

  /** Returns whether this optional field EW_FixTypeis available
    *
    * @return Whether the optional field is available (true) or not (false).
    */
  bool hasEW_FixType() const noexcept override;

  /** Enables the optional field such that getEW_FixType will return the optional field and not throw an exception when
    * invoked.
    *
    * @param type The value to set the optional field to
    * @return The accessor that provides access to the contents of the optional field accessed by this accesor
    */
  uci::type::EW_FixEnum& enableEW_FixType(uci::base::accessorType::AccessorType type = uci::base::accessorType::null) override;

  /** Clears the optional item marking it as not being set.
    *
    * @return A reference to the object on which this method was called.
    */
  uci::type::SignalEmitterKinematicsFixedType& clearEW_FixType() noexcept override;

  /** 
    *
    * @param type .
    * @return .
    */
  static std::unique_ptr<SignalEmitterKinematicsFixedType> create(uci::base::accessorType::AccessorType type);

  /** 
    *
    * @param propTree .
    * @param accessor .
    * @param nodeName .
    * @param nsPrefix .
    * @param topLevel .
    */
  static void deserialize(const boost::property_tree::ptree& propTree, uci::type::SignalEmitterKinematicsFixedType& accessor, std::string& nodeName, std::string& nsPrefix, bool topLevel = false);

  /** 
    *
    * @param accessor .
    * @param propTree .
    * @param nodeName .
    * @param createNode .
    * @param addTypeAttribute .
    * @param checkIfDerivation .
    * @param topLevel .
    * @return .
    */
  static std::string serialize(const uci::type::SignalEmitterKinematicsFixedType& accessor, boost::property_tree::ptree& propTree, const std::string& nodeName, bool createNode = true, bool addTypeAttribute = false, bool checkIfDerivation = true, bool topLevel = false);

private:
  std::unique_ptr<GeolocationStatus> geolocationStatus_Accessor;
  std::unique_ptr<EW_FixEnum> eW_FixType_Accessor;

};

} // namespace type

} // namespace asb_uci

#endif // ASB_UCI_TYPE_SIGNALEMITTERKINEMATICSFIXEDTYPE_H
