/** @file UnitIdentityType.h
 *
 * @warning This file is automatically generated, edit at your own risk
 *
 * This file was generated on 04/01/2024 at 02:25:15 PM
 *
 * <pre>
 * Unclassified               U N C L A S S I F I E D               Unclassified
 *
 * DISTRIBUTION STATEMENT D: Distribution authorized to Department of Defense
 *    and U.S. DoD contractors only, Critical Technology, Export Controlled,
 *    26 January 2023. Other requests for this document shall be referred to
 *    AFLCMC/XA (OAMO), Wright-Patterson AFB OH 45433.
 *
 * DESTRUCTION NOTICE: Destroy by any method that will prevent disclosure of
 *    contents or reconstruction of the document.
 *
 * WARNING - This document contains technical data whose export is restricted
 *    by the Arms Export Control Act (Section 2751 of Title 22, United States
 *    Code) or the Export Control Reform Act of 2018 (Chapter 58 Sections
 *    4801-4852 of Title 50, United States Code). Violations of these export
 *    laws are subject to severe criminal penalties. Disseminate in accordance
 *    with provisions of DoD Directive 5230.25 and DoD Instruction 2040.02.
 *
 * Controlled by: USAF
 * Controlled by: AFLCMC/XA (OAMO)
 * CUI Category(ies): CTI, EXPT
 * Distribution Statement D
 * POC: Wayne Artuso, 937-713-5124
 *
 * CUI//SP-CTI/SP-EXPT
 * </pre>
 *
 */

#ifndef ASB_UCI_TYPE_UNITIDENTITYTYPE_H
#define ASB_UCI_TYPE_UNITIDENTITYTYPE_H

#include <memory>

#include <boost/optional/optional.hpp>
#include <boost/property_tree/ptree.hpp>

#include "../../../include/asb_uci/base/BoundedList.h"
#include "../../../include/asb_uci/type/NameSpecialCharacterRestrictionType.h"
#include "../../../include/asb_uci/type/OrderOfBattleEnum.h"
#include "../../../include/asb_uci/type/String20Type.h"
#include "../../../include/asb_uci/type/UnitIdentifierType.h"
#include "../../../include/asb_uci/type/UnitNameType.h"
#include "../../../../cppInterface/2.3.2/include/uci/type/UnitIdentityType.h"

/**  */
namespace asb_uci {

/** The namespace in which all generated data types are declared */
namespace type {

class UnitID_Type;

/** See annotations in child elements and messages/elements that use this type for details. */
class UnitIdentityType : public virtual uci::type::UnitIdentityType {
public:
  /** Indicates the type of Order-of-Battle to which a unit or equipment belongs. List size for this element is based on
    * "Select All That Apply" condition. [Occurrences: Minimum: 1; Maximum: 11]
    */
  using OB_Type = asb_uci::base::BoundedList<uci::type::OrderOfBattleEnum, uci::type::accessorType::orderOfBattleEnum, asb_uci::type::OrderOfBattleEnum>;

  /** The constructor */
  UnitIdentityType();

  /** The copy constructor
    *
    * @param rhs The UnitIdentityType to copy from
    */
  UnitIdentityType(const UnitIdentityType& rhs) = delete;

  /** The move constructor
    *
    * @param rhs The UnitIdentityType to move from
    */
  UnitIdentityType(UnitIdentityType&& rhs) = delete;

  /** The assignment operator
    *
    * @param rhs The UnitIdentityType to copy from
    * @return The UnitIdentityType that was assigned
    */
  UnitIdentityType& operator=(const UnitIdentityType& rhs) = delete;

  /** The move assignment operator
    *
    * @param rhs The UnitIdentityType to move from
    * @return The UnitIdentityType that was assigned
    */
  UnitIdentityType& operator=(UnitIdentityType&& rhs) = delete;

  /** The destructor */
  virtual ~UnitIdentityType();

  /** Performs a deep copy of the message data from the specified accessor into the object being operated on by copy(). Any
    * message data originally held by this object will be freed prior to the copy
    *
    * @param accessor The uci::type::UnitIdentityType whose contents are to be used to set this
    *      uci::type::UnitIdentityType's contents.
    */
  void copy(const uci::type::UnitIdentityType& accessor) override;

  /** Performs a deep copy of the message data from the specified accessor into the object being operated on by copy(). Any
    * message data originally held by this object will be freed prior to the copy
    *
    * @param accessor The uci::type::UnitIdentityType whose contents are to be used to set this
    *      uci::type::UnitIdentityType's contents.
    * @param checkIfDerivation Check if accessor to copy is a derived type.
    */
  void copyImpl(const uci::type::UnitIdentityType& accessor, bool checkIfDerivation);

  /** Resets the contents of this object returning these contents to their original state. */
  void reset() noexcept override;

  /** Returns the accessor to the UnitUUID field contained in this message fragment
    *
    * @return The const reference to the accessor to the UnitUUID field.
    */
  const uci::type::UnitID_Type& getUnitUUID() const override;

  /** Returns the accessor to the UnitUUID field contained in this message fragment
    *
    * @return The reference to the accessor to the UnitUUID field.
    */
  uci::type::UnitID_Type& getUnitUUID() override;

  /** Set the contents of the message fragment that this accesssor provides access to to the contents the specified
    * accessor provides access to. A deep copy will be used by this method in setting the contents
    *
    * @param accessor The accessor to use to set the contents of the message fragment that this accessor provides access
    *      to.
    * @return A reference to the object on which this method was called.
    */
  uci::type::UnitIdentityType& setUnitUUID(const uci::type::UnitID_Type& accessor) override;

  /** Returns the contents of the message's Identifier field
    *
    * @return The contents of the Identifier field
    */
  const uci::type::UnitIdentifierType& getIdentifier() const noexcept override;

  /** Returns the contents of the message's Identifier field
    *
    * @return The contents of the Identifier field
    */
  uci::type::UnitIdentifierType& getIdentifier() noexcept override;

  /** Sets the contents of the message's Identifier field
    *
    * @param value The new value to set the Identifier field to
    * @return A reference to the object on which this method was called.
    */
  uci::type::UnitIdentityType& setIdentifier(const uci::type::UnitIdentifierType& value) override;

  /** Sets the contents of the message's Identifier field
    *
    * @param value The new value to set the Identifier field to
    * @return A reference to the object on which this method was called.
    */
  uci::type::UnitIdentityType& setIdentifier(const std::string& value) override;

  /** Sets the contents of the message's Identifier field
    *
    * @param value The new value to set the Identifier field to
    * @return A reference to the object on which this method was called.
    */
  uci::type::UnitIdentityType& setIdentifier(const char* value) override;

  /** Returns the contents of the message's Name field
    *
    * @return The contents of the Name field
    */
  const uci::type::UnitNameType& getName() const noexcept override;

  /** Returns the contents of the message's Name field
    *
    * @return The contents of the Name field
    */
  uci::type::UnitNameType& getName() noexcept override;

  /** Sets the contents of the message's Name field
    *
    * @param value The new value to set the Name field to
    * @return A reference to the object on which this method was called.
    */
  uci::type::UnitIdentityType& setName(const uci::type::UnitNameType& value) override;

  /** Sets the contents of the message's Name field
    *
    * @param value The new value to set the Name field to
    * @return A reference to the object on which this method was called.
    */
  uci::type::UnitIdentityType& setName(const std::string& value) override;

  /** Sets the contents of the message's Name field
    *
    * @param value The new value to set the Name field to
    * @return A reference to the object on which this method was called.
    */
  uci::type::UnitIdentityType& setName(const char* value) override;

  /** Returns the contents of the message's SurrogateKey field
    *
    * @return The contents of the SurrogateKey field
    */
  const uci::type::String20Type& getSurrogateKey() const noexcept override;

  /** Returns the contents of the message's SurrogateKey field
    *
    * @return The contents of the SurrogateKey field
    */
  uci::type::String20Type& getSurrogateKey() noexcept override;

  /** Sets the contents of the message's SurrogateKey field
    *
    * @param value The new value to set the SurrogateKey field to
    * @return A reference to the object on which this method was called.
    */
  uci::type::UnitIdentityType& setSurrogateKey(const uci::type::String20Type& value) override;

  /** Sets the contents of the message's SurrogateKey field
    *
    * @param value The new value to set the SurrogateKey field to
    * @return A reference to the object on which this method was called.
    */
  uci::type::UnitIdentityType& setSurrogateKey(const std::string& value) override;

  /** Sets the contents of the message's SurrogateKey field
    *
    * @param value The new value to set the SurrogateKey field to
    * @return A reference to the object on which this method was called.
    */
  uci::type::UnitIdentityType& setSurrogateKey(const char* value) override;

  /** Returns the accessor to the OB_Type field contained in this message fragment
    *
    * @return The const reference to the accessor to the OB_Type field.
    */
  const uci::type::UnitIdentityType::OB_Type& getOB_Type() const override;

  /** Returns the accessor to the OB_Type field contained in this message fragment
    *
    * @return The reference to the accessor to the OB_Type field.
    */
  uci::type::UnitIdentityType::OB_Type& getOB_Type() override;

  /** Set the contents of the message fragment that this accesssor provides access to to the contents the specified
    * accessor provides access to. A deep copy will be used by this method in setting the contents
    *
    * @param accessor The accessor to use to set the contents of the message fragment that this accessor provides access
    *      to.
    * @return A reference to the object on which this method was called.
    */
  uci::type::UnitIdentityType& setOB_Type(const uci::type::UnitIdentityType::OB_Type& accessor) override;

  /** Returns the value of the optional field accessed by this accesor
    *
    * @return The value of the optional field
    */
  uci::type::NameSpecialCharacterRestrictionType& getSymbolCode_() const;

  /** Returns the value of the optional field accessed by this accesor
    *
    * @return The value of the optional field
    */
  const uci::type::NameSpecialCharacterRestrictionType& getSymbolCode() const override;

  /** Returns the value of the optional field accessed by this accesor
    *
    * @return The value of the optional field
    */
  uci::type::NameSpecialCharacterRestrictionType& getSymbolCode() override;

  /** Sets the value of the optional field accessed by this accesor
    *
    * @param value The value to set the optional field to
    * @return A reference to the object on which this method was called.
    */
  uci::type::UnitIdentityType& setSymbolCode(const uci::type::NameSpecialCharacterRestrictionType& value) override;

  /** Sets the value of the optional field accessed by this accesor
    *
    * @param value The value to set the optional field to
    * @return A reference to the object on which this method was called.
    */
  uci::type::UnitIdentityType& setSymbolCode(const std::string& value) override;

  /** Sets the value of the optional field accessed by this accesor
    *
    * @param value The value to set the optional field to
    * @return A reference to the object on which this method was called.
    */
  uci::type::UnitIdentityType& setSymbolCode(const char* value) override;

  /** Returns whether this optional field symbolCode_is available
    *
    * @return Whether the optional field is available (true) or not (false).
    */
  bool hasSymbolCode() const noexcept override;

  /** Enables the optional field such that getSymbolCode will return the optional field and not throw an exception when
    * invoked.
    *
    * @param type The value to set the optional field to
    * @return The value of the optional field
    */
  uci::type::NameSpecialCharacterRestrictionType& enableSymbolCode(uci::base::accessorType::AccessorType type = uci::base::accessorType::null) override;

  /** Clears the optional item marking it as not being set.
    *
    * @return A reference to the object on which this method was called.
    */
  uci::type::UnitIdentityType& clearSymbolCode() noexcept override;

  /** 
    *
    * @param type .
    * @return .
    */
  static std::unique_ptr<UnitIdentityType> create(uci::base::accessorType::AccessorType type);

  /** 
    *
    * @param propTree .
    * @param accessor .
    * @param nodeName .
    * @param nsPrefix .
    * @param topLevel .
    */
  static void deserialize(const boost::property_tree::ptree& propTree, uci::type::UnitIdentityType& accessor, std::string& nodeName, std::string& nsPrefix, bool topLevel = false);

  /** 
    *
    * @param accessor .
    * @param propTree .
    * @param nodeName .
    * @param createNode .
    * @param addTypeAttribute .
    * @param checkIfDerivation .
    * @param topLevel .
    * @return .
    */
  static std::string serialize(const uci::type::UnitIdentityType& accessor, boost::property_tree::ptree& propTree, const std::string& nodeName, bool createNode = true, bool addTypeAttribute = false, bool checkIfDerivation = true, bool topLevel = false);

private:
  std::unique_ptr<UnitID_Type> unitUUID_Accessor;
  std::unique_ptr<UnitIdentifierType> identifier_Accessor;
  std::unique_ptr<UnitNameType> name_Accessor;
  std::unique_ptr<String20Type> surrogateKey_Accessor;
  std::unique_ptr<OB_Type> oB_Type_Accessor;
  std::unique_ptr<NameSpecialCharacterRestrictionType> symbolCode_Accessor;

};

} // namespace type

} // namespace asb_uci

#endif // ASB_UCI_TYPE_UNITIDENTITYTYPE_H
